/**
 * Aria icon catalog.
 * Kept as the semantic key → Hugeicons slug map.
 * Runtime rendering in aria-app uses `registry.ts` + `AppIcon` (component icons).
 */

export const studioIcons = {
  // Navigation & panels
  dashboard: "i-hugeicons:home-02",
  pages: "i-hugeicons:align-box-middle-center",
  studio: "i-hugeicons:align-box-middle-center",
  composer: "i-hugeicons:cursor-edit-01",
  layouts: "i-hugeicons:brochure",
  layoutPivot: "i-hugeicons:pivot",
  components: "i-hugeicons:keyframe",
  collections: "i-hugeicons:quill-write-01",
  media: "i-hugeicons:image-01",
  design: "i-hugeicons:colors",
  settings: "i-hugeicons:preference-vertical",
  settings01: "i-hugeicons:settings-01",
  search: "i-hugeicons:search-01",
  history: "i-hugeicons:time-schedule",
  transactionHistory: "i-hugeicons:transaction-history",
  users: "i-hugeicons:user-group",
  security: "i-hugeicons:blocked",
  user: "i-hugeicons:user",
  help: "i-hugeicons:help-circle",
  webDesign: "i-hugeicons:web-design-01",
  terminal: "i-hugeicons:terminal",

  // Chevrons & arrows
  chevronRight: "i-hugeicons:arrow-right-01",
  chevronDown: "i-hugeicons:arrow-down-01",
  chevronUp: "i-hugeicons:arrow-up-01",
  chevronLeft: "i-hugeicons:arrow-left-01",
  arrowRight: "i-hugeicons:arrow-right-02",
  arrowLeft: "i-hugeicons:arrow-left-02",
  arrowUp: "i-hugeicons:arrow-up-02",
  arrowDown: "i-hugeicons:arrow-down-02",
  arrowLeft03: "i-hugeicons:arrow-left-03",
  arrowRight03: "i-hugeicons:arrow-right-03",
  arrowUpDown: "i-hugeicons:arrow-up-down",
  arrowLeftRight: "i-hugeicons:arrow-left-right",
  arrowUpLeft: "i-hugeicons:arrow-up-left-01",
  arrowUpRight: "i-hugeicons:arrow-up-right-01",
  arrowDownRight: "i-hugeicons:arrow-down-right-01",
  arrowDownLeft: "i-hugeicons:arrow-down-left-01",
  arrowReloadHorizontal: "i-hugeicons:arrow-reload-horizontal",
  arrowExpand: "i-hugeicons:arrow-expand-01",
  arrowLeftLinear: "i-hugeicons:arrow-left-01",
  externalLink: "i-hugeicons:external-link",
  move: "i-hugeicons:move-01",
  toolbarMove: "i-hugeicons:move",

  // Actions
  plus: "i-hugeicons:add-01",
  add: "i-hugeicons:add-01",
  addCircle: "i-hugeicons:plus-sign-circle",
  addCircleLinear: "i-hugeicons:add-circle",
  addSquare: "i-hugeicons:add-square",
  plusSign: "i-hugeicons:plus-sign",
  edit: "i-hugeicons:edit-01",
  edit03: "i-hugeicons:edit-03",
  trash: "i-hugeicons:delete-01",
  trashBin: "i-hugeicons:delete-02",
  duplicate: "i-hugeicons:copy-01",
  copy: "i-hugeicons:copy-01",
  play: "i-hugeicons:play",
  rename: "i-hugeicons:cursor-text",
  save: "i-hugeicons:floppy-disk",
  publish: "i-hugeicons:play",
  unpublish: "i-hugeicons:pause",
  shutDown: "i-hugeicons:shut-down",
  close: "i-hugeicons:cancel-01",
  closeCircleBold: "i-hugeicons:cancel-circle",
  check: "i-hugeicons:checkmark-square-02",
  checkSmall: "i-hugeicons:checkmark-square-01",
  checkCircle: "i-hugeicons:checkmark-circle-01",
  checkCircleBold: "i-hugeicons:checkmark-circle-01",
  checkCircleLinear: "i-hugeicons:checkmark-circle-02",
  checkLinear: "i-hugeicons:tick-01",
  warning: "i-hugeicons:alert-01",
  info: "i-hugeicons:information-diamond",
  filter: "i-hugeicons:filter",
  filterRemove: "i-hugeicons:filter-remove",
  sort: "i-hugeicons:arrow-up-down",
  refresh: "i-hugeicons:refresh",
  refreshLine: "i-hugeicons:refresh",
  upload: "i-hugeicons:upload-01",
  download: "i-hugeicons:download-01",
  share: "i-hugeicons:share-01",
  link: "i-hugeicons:link-02",
  linkBold: "i-hugeicons:link-02",
  linkLine: "i-hugeicons:link-02",
  unlink: "i-hugeicons:unlink-02",
  unlink02: "i-hugeicons:unlink-02",
  lock: "i-hugeicons:lock-password",
  unlock: "i-hugeicons:square-unlock-01",
  moreHorizontal: "i-hugeicons:more-horizontal-square-01",
  moreVertical: "i-hugeicons:more-vertical-square-01",
  menu: "i-hugeicons:hamburger-01",
  menu01: "i-hugeicons:menu-01",
  grid: "i-hugeicons:grid-view",
  list: "i-hugeicons:menu-02",
  listBulleted: "i-hugeicons:left-to-right-list-bullet",
  listNumbered: "i-hugeicons:left-to-right-list-number",
  listDescription: "i-hugeicons:list-tree",
  preview: "i-hugeicons:view",
  maximize: "i-hugeicons:maximize-01",
  minimize: "i-hugeicons:minimize-01",
  collapse: "i-hugeicons:arrow-data-transfer-horizontal",
  expand: "i-hugeicons:arrow-data-transfer-horizontal",
  expandHuge: "i-hugeicons:expand",
  fitWidth: "i-hugeicons:zoom-out-area",
  actualSize: "i-hugeicons:zoom-in-area",
  zoomOut: "i-hugeicons:minus-sign",
  zoomIn: "i-hugeicons:plus-sign",
  columns: "i-hugeicons:column-insert",
  layers: "i-hugeicons:layer",
  tuning: "i-hugeicons:sliders-horizontal",
  aiMic: "i-hugeicons:ai-mic",
  unarchive: "i-hugeicons:unarchive-03",

  // Theme & appearance
  sun: "i-hugeicons:sun-01",
  moon: "i-hugeicons:moon-02",
  themeSun: "i-hugeicons:sun-02",
  themeMoon: "i-hugeicons:moon-02",
  sunLinear: "i-hugeicons:sun-01",
  sunFog: "i-hugeicons:sun-cloud-01",
  sunFogLine: "i-hugeicons:sun-cloud-02",

  // Status
  published: "i-hugeicons:checkmark-circle-01",
  draft: "i-hugeicons:edit-02",
  archived: "i-hugeicons:archive-03",
  archive: "i-hugeicons:archive-01",
  pending: "i-hugeicons:time-schedule",

  // Content types & nodes
  page: "i-hugeicons:file-01",
  pageChild: "i-hugeicons:pathfinder-minus-front",
  pageSpecial: "i-hugeicons:settings-05",
  component: "i-hugeicons:keyframe",
  pageLayout: "i-hugeicons:workflow-circle-02",
  componentBlock: "i-hugeicons:component",
  image: "i-hugeicons:image-01",
  imageUpload: "i-hugeicons:image-upload",
  scanImage: "i-hugeicons:scan-image",
  video: "i-hugeicons:video-01",
  file: "i-hugeicons:file-01",
  folder: "i-hugeicons:folder-01",
  folderAdd: "i-hugeicons:folder-add",
  code: "i-hugeicons:source-code",
  codeSquare: "i-hugeicons:code-square",
  code2Line: "i-hugeicons:code",
  text: "i-hugeicons:text",
  textLine: "i-hugeicons:text",
  home: "i-hugeicons:home-01",
  element: "i-hugeicons:square",
  section: "i-hugeicons:square-arrow-expand-01",
  boxLine: "i-hugeicons:bounding-box",
  widgetAdd: "i-hugeicons:keyframe-add",
  widget4: "i-hugeicons:layout-04",
  databaseLine: "i-hugeicons:database-01",
  groupLayers: "i-hugeicons:group-layers",
  hardDrive: "i-hugeicons:hard-drive",
  infoCircle: "i-hugeicons:information-circle",
  task: "i-hugeicons:task-01",

  // Editor & typography
  bold: "i-hugeicons:text-bold",
  italic: "i-hugeicons:text-italic",
  underline: "i-hugeicons:underline-01",
  strikethrough: "i-hugeicons:text-strikethrough",
  alignLeft: "i-hugeicons:align-left",
  alignCenter: "i-hugeicons:align-center",
  alignRight: "i-hugeicons:align-right",
  alignTop: "i-hugeicons:align-top",
  alignBottom: "i-hugeicons:align-bottom",
  alignHorizontalCenter: "i-hugeicons:align-horizontal-center",
  alignVerticalCenter: "i-hugeicons:align-vertical-center",
  alignHorizontalSpaceBetween: "i-hugeicons:align-horizontal-space-between",
  alignVerticalSpaceBetween: "i-hugeicons:align-vertical-space-between",
  alignHorizontalDistributeStart:
    "i-hugeicons:align-horizontal-distribute-start",
  alignVerticalDistributeCenter: "i-hugeicons:align-vertical-distribute-center",
  alignBoxTopCenter: "i-hugeicons:align-box-top-center",
  alignBoxMiddleCenter: "i-hugeicons:align-box-middle-center",
  alignBoxBottomCenter: "i-hugeicons:align-box-bottom-center",
  alignHorizontalSpacing: "i-hugeicons:distribute-horizontal-center",
  undo: "i-hugeicons:undo-03",
  redo: "i-hugeicons:redo-03",
  eye: "i-hugeicons:eye",
  eyeOff: "i-hugeicons:view-off",
  notEqualSign: "i-hugeicons:not-equal-sign",
  textWrap: "i-hugeicons:text-wrap",
  textFontSize: "i-hugeicons:text-font",
  headingNode: "i-hugeicons:heading",
  buttonLayer: "i-hugeicons:cursor-rectangle-selection-02",
  clipboard: "i-hugeicons:clipboard",
  layoutGrid: "i-hugeicons:layout-grid",
  layoutTwoColumn: "i-hugeicons:layout-two-column",
  layoutTwoRow: "i-hugeicons:layout-two-row",
  creditCard: "i-hugeicons:credit-card",
  lineHeight: "i-hugeicons:paragraph-spacing",
  letterSpacing: "i-hugeicons:letter-spacing",

  // Design system
  typography: "i-hugeicons:text-font",
  colorPalette: "i-hugeicons:paint-board",
  paletteLinear: "i-hugeicons:color-picker",
  designLayout: "i-hugeicons:layout-01",
  spacing: "i-hugeicons:space-width",
  border: "i-hugeicons:border-right",
  shadow: "i-hugeicons:artboard",
  radius: "i-hugeicons:join-round",
  rounding: "i-hugeicons:join-round",
  strokeCenter: "i-hugeicons:stroke-center",
  blur: "i-hugeicons:blur",
  moveHorizontal: "i-hugeicons:arrow-data-transfer-horizontal",
  moveVertical: "i-hugeicons:arrow-data-transfer-vertical",
  circleHalf: "i-hugeicons:dark-mode",
  waterdrop: "i-hugeicons:droplet",
  layersLinear: "i-hugeicons:layer",
  dropLinear: "i-hugeicons:paint-bucket",
  closeSquare: "i-hugeicons:cancel-square",
  threeSquares: "i-hugeicons:three-square",
  galleryBold: "i-hugeicons:image-01",
  galleryLinear: "i-hugeicons:album-01",
  galleryWide: "i-hugeicons:gallery-horizontal-end",
  uploadLine: "i-hugeicons:upload-01",
  audioWave: "i-hugeicons:audio-wave-01",
  slidersVertical: "i-hugeicons:sliders-vertical",
  variable: "i-hugeicons:orthogonal-edge",

  // Media & communication
  mail: "i-hugeicons:mail-01",
  globe: "i-hugeicons:global",
  phone: "i-hugeicons:telephone",
  calendar: "i-hugeicons:calendar-01",
  clock: "i-hugeicons:clock-01",
  schedule: "i-hugeicons:time-schedule",
  tag: "i-hugeicons:tag-01",
  flag: "i-hugeicons:flag-01",
  bookmark: "i-hugeicons:bookmark-01",
  star: "i-hugeicons:star",
  starLine: "i-hugeicons:star",
  heart: "i-hugeicons:favourite",
  gift: "i-hugeicons:gift",
  activity: "i-hugeicons:activity-01",
  inbox: "i-hugeicons:inbox",
  energy: "i-hugeicons:energy",
  rotateClockwise: "i-hugeicons:rotate-clockwise",
  magnifier: "i-hugeicons:search-01",

  // Charts & analytics
  chart: "i-hugeicons:chart-01",
  barChart: "i-hugeicons:bar-chart",
  pieChart: "i-hugeicons:pie-chart-01",
  trendUp: "i-hugeicons:trend-up-01",
  trendDown: "i-hugeicons:trend-down-01",

  // Auth & security
  login: "i-hugeicons:login-01",
  logout: "i-hugeicons:logout-square-01",
  signOut: "i-hugeicons:logout-02",
  key: "i-hugeicons:key-01",
  keyLine: "i-hugeicons:key-01",
  shield: "i-hugeicons:shield-01",
  shieldLine: "i-hugeicons:shield-01",
  shieldKeyhole: "i-hugeicons:shield-key",
  shieldCheck: "i-hugeicons:security-check",
  userPlus: "i-hugeicons:user-add-02",
  userLine: "i-hugeicons:user",
  userCircle: "i-hugeicons:user-circle",
  penLine: "i-hugeicons:pen-01",
  dangerTriangle: "i-hugeicons:alert-01",

  // Stage toolbar
  selectParent: "i-hugeicons:layer-bring-forward",
  createComponent: "i-hugeicons:keyframe-add",
  detachComponent: "i-hugeicons:keyframes-double-remove",
  editComponent: "i-hugeicons:edit-03",

  // Inspector
  inspectorTabProps: "i-hugeicons:arrow-data-transfer-horizontal",
  props: "i-hugeicons:arrow-data-transfer-horizontal",
  inspectorTabLogic: "i-hugeicons:usb",
  branchingPaths: "i-hugeicons:git-branch",
  cursorLine: "i-hugeicons:cursor-01",
  lightning: "i-hugeicons:flash",
  mapArrowLeftBold: "i-hugeicons:arrow-turn-backward",
  pseudoState: "i-hugeicons:centralized",
  windowFrame: "i-hugeicons:browser",
  sidebarMinimal: "i-hugeicons:sidebar-left",
  microphone: "i-hugeicons:mic-01",

  // Devices & breakpoints
  monitor: "i-hugeicons:computer",
  laptop: "i-hugeicons:laptop",
  tablet: "i-hugeicons:tablet-01",
  smartphone: "i-hugeicons:smart-phone-01",

  // Misc
  accessibility: "i-hugeicons:cursor-magic-selection-03",
  loading: "i-hugeicons:loading-01",
  dragHandle: "i-hugeicons:drag-drop-horizontal",
  cursor: "i-hugeicons:cursor-01",
  target: "i-hugeicons:target-01",
  pin: "i-hugeicons:pin-01",
  local: "i-hugeicons:lock",
  notification: "i-hugeicons:notification-01",
  sparkles: "i-hugeicons:stars",
} as const;

export type StudioIconKey = keyof typeof studioIcons;

// Class category icons (Inspector ClassesProperty)

export const classCategoryIcons: Record<string, string> = {
  LayoutGrid: "i-hugeicons:grid-view",
  Rows3: "i-hugeicons:distribute-horizontal-center",
  Grid3x3: "i-hugeicons:layout-grid",
  Space: "i-hugeicons:paragraph-spacing",
  Scaling: "i-hugeicons:3d-scale",
  Type: "i-hugeicons:text-bold",
  Palette: "i-hugeicons:paint-board",
  Square: "i-hugeicons:structure-01",
  Sparkles: "i-hugeicons:magic-wand-01",
  Move: "i-hugeicons:cursor-01",
};

// Pseudo category icons (Inspector PseudoSelectorDropdown)

export const pseudoCategoryIcons: Record<string, string> = {
  MousePointer: "i-hugeicons:cursor-01",
  FormInput: "i-hugeicons:input-text",
  Layers: "i-hugeicons:layers-01",
  Share2: "i-hugeicons:share-01",
  Sparkles: "i-hugeicons:magic-wand-01",
};

// Node-type icons (Inspector header)

export const inspectorNodeTypeIcons: Record<string, string> = {
  container: studioIcons.boxLine,
  section: studioIcons.boxLine,
  div: studioIcons.boxLine,
  block: studioIcons.boxLine,
  text: studioIcons.textLine,
  heading: studioIcons.textLine,
  paragraph: studioIcons.textLine,
  image: studioIcons.galleryLinear,
  img: studioIcons.galleryLinear,
  link: studioIcons.linkLine,
  a: studioIcons.linkLine,
  button: studioIcons.cursorLine,
  default: studioIcons.widgetAdd,
};

// Node-type icons (Layers panel)

export const layerNodeTypeIcons: Record<string, string> = {
  component: studioIcons.component,
  heading: studioIcons.headingNode,
  text: studioIcons.textFontSize,
  paragraph: studioIcons.textFontSize,
  image: studioIcons.galleryLinear,
  button: studioIcons.buttonLayer,
  link: studioIcons.link,
  list: studioIcons.list,
  listIcon: studioIcons.task,
  listitem: studioIcons.checkSmall,
  listitemIcon: studioIcons.checkCircleLinear,
  icon: studioIcons.star,
  section: studioIcons.section,
  container: studioIcons.element,
  layout: studioIcons.element,
  default: studioIcons.element,
};

// Canvas overlay toolbar icons (Stage)

export const toolbarIcons = {
  selectParent: studioIcons.selectParent,
  drag: studioIcons.toolbarMove,
  createComponent: studioIcons.createComponent,
  detachComponent: studioIcons.detachComponent,
  editComponent: studioIcons.editComponent,
  duplicate: studioIcons.duplicate,
  delete: studioIcons.trash,
  component: studioIcons.component,
  element: studioIcons.element,
  section: studioIcons.section,
  icon: studioIcons.star,
  openMediaPicker: studioIcons.imageUpload,
  loop: studioIcons.inspectorTabProps,
  motion: studioIcons.lightning,
} as const;

// Background mode icons (Inspector BackgroundProperty)

export const backgroundModeIcons = {
  none: studioIcons.closeSquare,
  color: studioIcons.colorPalette,
  gradient: studioIcons.threeSquares,
  image: studioIcons.galleryBold,
} as const;

// Safelist — all registry icons used in dynamic :class bindings

const allIconMaps = [
  studioIcons,
  classCategoryIcons,
  inspectorNodeTypeIcons,
  layerNodeTypeIcons,
  toolbarIcons,
  backgroundModeIcons,
  pseudoCategoryIcons,
] as const;

export const studioIconSafelist = [
  ...new Set(allIconMaps.flatMap((map) => Object.values(map))),
] as const;
