/**
 * Source for the Vite-injected design client (Phase 1 bridge vehicle B).
 *
 * Always loads in the live Astro preview iframe (Vite `injectScript`).
 * - Interactive URL (no `#aria-design` / `?aria-design`): strip marker `<template>`s
 *   only — keep DOM clean for browse (nth-child / flex). Used by external browser preview.
 * - Design hash: strip + stamp `data-aria-p`, postMessage bridge. Host can soft-toggle
 *   `aria:design-interaction` so a hidden Stage does not keep selection chrome live.
 *   Preview's all-breakpoints board posts `aria:set-vh` so vh units stay one screen tall.
 * Never exposes `window.aria` or any Electron IPC.
 */

import {
  ARIA_DESIGN_HASH,
  ARIA_DESIGN_QUERY,
  ARIA_MARKER_END,
  ARIA_MARKER_START,
  ARIA_PATH_ATTR,
} from "../../shared/composer/constants";
import {
  ARIA_BRIDGE_ID,
  ARIA_MSG,
  ARIA_PROTOCOL_VERSION,
} from "../../shared/composer/protocol";
import { ARIA_COMPOSER_CLIPBOARD_MIME } from "../../shared/composer/clipboard";
import {
  COMPOSER_IMAGE_PLACEHOLDER_SRC,
  LEGACY_BRANDED_COMPOSER_IMAGE_PLACEHOLDER_SRC,
  LEGACY_COMPOSER_IMAGE_PLACEHOLDER_SRC,
} from "../../shared/composer/ariaPrimitives";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";

const require = createRequire(import.meta.url);
const MORPHDOM_SOURCE = readFileSync(
  require.resolve("morphdom/dist/morphdom-umd.min.js"),
  "utf8",
);

const DISPLAY_MODE_STYLES = `
html [data-aria-condition-failed] {
  outline: 1px dashed color-mix(in srgb, #f59e0b 65%, transparent) !important;
  outline-offset: 2px !important;
}
html[data-aria-composer-display="outlines"] [${ARIA_PATH_ATTR}] {
  outline: 1.5px dashed color-mix(in srgb, var(--aria-composer-accent, #0f9f73) 55%, transparent) !important;
  outline-offset: -1px !important;
}
html[data-aria-composer-display="wireframe"] { background: #f8fafc !important; }
html[data-aria-composer-display="wireframe"] body {
  background: linear-gradient(rgba(148,163,184,.07) 1px,transparent 1px), linear-gradient(90deg,rgba(148,163,184,.07) 1px,transparent 1px), #fcfcfd !important;
  background-size: 24px 24px !important;
  color: #334155 !important;
}
html[data-aria-composer-display="wireframe"] [${ARIA_PATH_ATTR}],
html[data-aria-composer-display="wireframe"] [${ARIA_PATH_ATTR}] * {
  background-image: none !important; box-shadow: none !important; text-shadow: none !important;
  filter: none !important; backdrop-filter: none !important;
}
html[data-aria-composer-display="wireframe"] [${ARIA_PATH_ATTR}] {
  min-height: 1.5rem; border: 1px dashed rgba(71,85,105,.55) !important;
  background-color: rgba(255,255,255,.84) !important; color: #334155 !important; outline: none !important;
}
html[data-aria-composer-display="wireframe"] [${ARIA_PATH_ATTR}]:empty { min-height: 2rem; }
html[data-aria-composer-display="wireframe"] [${ARIA_PATH_ATTR}] :is(img,video,iframe,svg) {
  opacity: .2 !important; border: 1px dashed rgba(100,116,139,.75) !important;
  background: repeating-linear-gradient(135deg,rgba(148,163,184,.18),rgba(148,163,184,.18) 8px,rgba(226,232,240,.4) 8px,rgba(226,232,240,.4) 16px) !important;
}
html[data-aria-composer-display="wireframe"] [${ARIA_PATH_ATTR}] :is(button,a,input,textarea,select) {
  border: 1px dashed rgba(71,85,105,.55) !important; background: rgba(241,245,249,.92) !important; color: #334155 !important;
}
html[data-aria-composer-display="wireframe"] [${ARIA_PATH_ATTR}] :is(h1,h2,h3,h4,h5,h6) {
  color: #0f172a !important; letter-spacing: 0 !important; text-transform: none !important;
}`;

/** Inline ES module body written to `node_modules/.aria/design-client.js`. */
export const DESIGN_CLIENT_SOURCE = `/* Generated by Aria (dev preview only) — do not edit. */
${MORPHDOM_SOURCE}
(() => {
  const DESIGN_HASH = ${JSON.stringify(ARIA_DESIGN_HASH)};
  const DESIGN_QUERY = ${JSON.stringify(ARIA_DESIGN_QUERY)};
  const MARKER_S = ${JSON.stringify(ARIA_MARKER_START)};
  const MARKER_E = ${JSON.stringify(ARIA_MARKER_END)};
  const PATH_ATTR = ${JSON.stringify(ARIA_PATH_ATTR)};
  const OCCURRENCE_ATTR = "data-aria-occurrence";
  const MSG = {
    ready: ${JSON.stringify(ARIA_MSG.ready)},
    bridgePing: ${JSON.stringify(ARIA_MSG.bridgePing)},
    rects: ${JSON.stringify(ARIA_MSG.rects)},
    hover: ${JSON.stringify(ARIA_MSG.hover)},
    click: ${JSON.stringify(ARIA_MSG.click)},
    open: ${JSON.stringify(ARIA_MSG.open)},
    track: ${JSON.stringify(ARIA_MSG.track)},
    scrollTo: ${JSON.stringify(ARIA_MSG.scrollTo)},
    viewport: ${JSON.stringify(ARIA_MSG.viewport)},
    restoreViewport: ${JSON.stringify(ARIA_MSG.restoreViewport)},
    shortcut: ${JSON.stringify(ARIA_MSG.shortcut)},
    paste: ${JSON.stringify(ARIA_MSG.paste)},
    dragOver: ${JSON.stringify(ARIA_MSG.dragOver)},
    dragLeave: ${JSON.stringify(ARIA_MSG.dragLeave)},
    dropHit: ${JSON.stringify(ARIA_MSG.dropHit)},
    previewStyle: ${JSON.stringify(ARIA_MSG.previewStyle)},
    clearPreviewStyle: ${JSON.stringify(ARIA_MSG.clearPreviewStyle)},
    syncMotionAssets: ${JSON.stringify(ARIA_MSG.syncMotionAssets)},
    syncFontStylesheet: ${JSON.stringify(ARIA_MSG.syncFontStylesheet)},
    patchNodes: ${JSON.stringify(ARIA_MSG.patchNodes)},
    inlineTextRequest: ${JSON.stringify(ARIA_MSG.inlineTextRequest)},
    inlineTextStart: ${JSON.stringify(ARIA_MSG.inlineTextStart)},
    inlineTextStartResult: ${JSON.stringify(ARIA_MSG.inlineTextStartResult)},
    inlineTextChange: ${JSON.stringify(ARIA_MSG.inlineTextChange)},
    inlineTextFinish: ${JSON.stringify(ARIA_MSG.inlineTextFinish)},
    inlineTextResult: ${JSON.stringify(ARIA_MSG.inlineTextResult)},
    patchResult: ${JSON.stringify(ARIA_MSG.patchResult)},
    reconcile: ${JSON.stringify(ARIA_MSG.reconcile)},
    reconcileResult: ${JSON.stringify(ARIA_MSG.reconcileResult)},
    computedStyleRequest: ${JSON.stringify(ARIA_MSG.computedStyleRequest)},
    computedStyleResponse: ${JSON.stringify(ARIA_MSG.computedStyleResponse)},
    displayOptions: ${JSON.stringify(ARIA_MSG.displayOptions)},
    designInteraction: ${JSON.stringify(ARIA_MSG.designInteraction)},
    popoverPreview: ${JSON.stringify(ARIA_MSG.popoverPreview)},
    setVh: ${JSON.stringify(ARIA_MSG.setVh)},
    pageHeight: ${JSON.stringify(ARIA_MSG.pageHeight)},
  };
  const CLIPBOARD_MIME = ${JSON.stringify(ARIA_COMPOSER_CLIPBOARD_MIME)};
  const IMAGE_PLACEHOLDER_SRC = ${JSON.stringify(COMPOSER_IMAGE_PLACEHOLDER_SRC)};
  const LEGACY_BRANDED_IMAGE_PLACEHOLDER_SRC = ${JSON.stringify(LEGACY_BRANDED_COMPOSER_IMAGE_PLACEHOLDER_SRC)};
  const LEGACY_IMAGE_PLACEHOLDER_SRC = ${JSON.stringify(LEGACY_COMPOSER_IMAGE_PLACEHOLDER_SRC)};
  const morphdom = window.morphdom;
  const frameToken = (() => { try { return new URL(location.href).searchParams.get("aria-frame") || ""; } catch { return ""; } })();
  const diagnostics = window.__ariaComposerDiagnostics || (window.__ariaComposerDiagnostics = {
    patches: 0, morphs: 0, preventedFullReloads: 0, reloadReasons: {},
  });
  const nextFrame = typeof window.requestAnimationFrame === "function"
    ? window.requestAnimationFrame.bind(window)
    : (callback) => window.setTimeout(callback, 0);

  let previewPopoverTargetId = null;
  let previewPopoverScheduled = false;
  const popoverTarget = (id) => id ? document.getElementById(id) : null;
  const isPopoverOpen = (target) => {
    try { return target.matches(":popover-open"); } catch { return false; }
  };
  const closePreviewPopover = (clear = true) => {
    const target = popoverTarget(previewPopoverTargetId);
    if (target && typeof target.hidePopover === "function" && isPopoverOpen(target)) {
      try { target.hidePopover(); } catch { /* invalid state */ }
    }
    if (clear) previewPopoverTargetId = null;
  };
  const applyPopoverPreview = () => {
    previewPopoverScheduled = false;
    const id = previewPopoverTargetId;
    if (!id) return;
    const target = popoverTarget(id);
    if (!target || typeof target.showPopover !== "function" || isPopoverOpen(target)) return;
    const source = Array.from(document.querySelectorAll("button[popovertarget]"))
      .find((candidate) => candidate.getAttribute("popovertarget") === id) || null;
    try { target.showPopover(source ? { source } : undefined); } catch { /* invalid state */ }
  };
  const queuePopoverPreview = () => {
    if (previewPopoverScheduled || !previewPopoverTargetId) return;
    previewPopoverScheduled = true;
    nextFrame(applyPopoverPreview);
  };

  function isDesignMode() {
    try {
      if (location.hash.includes(DESIGN_HASH)) return true;
      const q = new URLSearchParams(location.search);
      if (q.has(DESIGN_QUERY)) return true;
    } catch {
      /* ignore */
    }
    return false;
  }

  /**
   * Always strip marker <template> nodes — even in Interactive browse.
   * Leaving them in the DOM changes :first-child / :nth-child / flex-item
   * counts (Stacki’s preload strips unconditionally for the same reason).
   * Path stamping is design-only; interactive only needs a clean DOM.
   */
  const stripMarkers = () => {
    document
      .querySelectorAll(
        "template[" + MARKER_S + "], template[" + MARKER_E + "]",
      )
      .forEach((t) => t.remove());
  };

  if (!isDesignMode()) {
    if (document.readyState === "loading") {
      window.addEventListener("DOMContentLoaded", stripMarkers);
    } else {
      stripMarkers();
    }
    return;
  }

  const transientScrollbarsEnabled =
    (/^(Win|Linux)/i.test(navigator.platform || "") ||
      /\\b(Windows|Linux)\\b/i.test(navigator.userAgent || "")) &&
    !(typeof matchMedia === "function" && matchMedia("(forced-colors: active)").matches);
  const transientScrollbarStates = new WeakMap();
  const installTransientScrollbarStyles = () => {
    if (!transientScrollbarsEnabled || document.getElementById("aria-transient-scrollbars")) return;
    document.documentElement.setAttribute("data-aria-transient-scrollbars", "");
    const style = document.createElement("style");
    style.id = "aria-transient-scrollbars";
    style.textContent = [
      "@media (forced-colors: none) {",
      "html[data-aria-transient-scrollbars], html[data-aria-transient-scrollbars] * { scrollbar-color: transparent transparent; scrollbar-width: thin; }",
      "html[data-aria-transient-scrollbars][data-aria-scroll-active], html[data-aria-transient-scrollbars] [data-aria-scroll-active] { scrollbar-color: rgb(117 117 117) transparent; }",
      "}",
    ].join("\\n");
    (document.head || document.documentElement).appendChild(style);
  };
  const showTransientScrollbar = (event) => {
    if (!transientScrollbarsEnabled) return;
    const element = event.target instanceof Element
      ? event.target
      : document.documentElement;
    const previous = transientScrollbarStates.get(element);
    if (previous) {
      clearTimeout(previous.timer);
      previous.animation?.cancel();
    }
    element.setAttribute("data-aria-scroll-active", "");
    const state = { timer: 0, animation: null };
    state.timer = window.setTimeout(() => {
      const reducedMotion = typeof matchMedia === "function" &&
        matchMedia("(prefers-reduced-motion: reduce)").matches;
      if (reducedMotion || typeof element.animate !== "function") {
        element.removeAttribute("data-aria-scroll-active");
        transientScrollbarStates.delete(element);
        return;
      }
      let animation;
      try {
        animation = element.animate(
          [
            { scrollbarColor: "rgb(117 117 117) transparent" },
            { scrollbarColor: "transparent transparent" },
          ],
          {
            duration: 180,
            easing: "cubic-bezier(0.2, 0, 0, 1)",
            fill: "forwards",
          },
        );
      } catch {
        element.removeAttribute("data-aria-scroll-active");
        transientScrollbarStates.delete(element);
        return;
      }
      state.animation = animation;
      element.removeAttribute("data-aria-scroll-active");
      animation.onfinish = () => {
        if (transientScrollbarStates.get(element)?.animation !== animation) return;
        animation.cancel();
        transientScrollbarStates.delete(element);
      };
    }, 650);
    transientScrollbarStates.set(element, state);
  };

  // Older Image primitives persisted a project-root URL that often did not exist.
  // Recover only after that exact legacy source fails; a real project file wins.
  window.addEventListener("error", (event) => {
    const image = event.target;
    if (image instanceof HTMLImageElement && image.getAttribute("src") === "/placeholder.svg") {
      image.src = IMAGE_PLACEHOLDER_SRC;
    }
  }, true);

  const refreshLegacyImagePlaceholders = (root) => {
    const images = [];
    if (root instanceof HTMLImageElement) images.push(root);
    if (root?.querySelectorAll) images.push(...root.querySelectorAll("img"));
    for (const image of images) {
      if (
        image.getAttribute("src") === LEGACY_IMAGE_PLACEHOLDER_SRC ||
        image.getAttribute("src") === LEGACY_BRANDED_IMAGE_PLACEHOLDER_SRC
      ) {
        image.src = IMAGE_PLACEHOLDER_SRC;
      }
    }
  };
  const placeholderObserver = new MutationObserver((records) => {
    for (const record of records) {
      if (record.type === "attributes") refreshLegacyImagePlaceholders(record.target);
      for (const node of record.addedNodes || []) refreshLegacyImagePlaceholders(node);
    }
  });
  placeholderObserver.observe(document.documentElement, {
    subtree: true,
    childList: true,
    attributes: true,
    attributeFilter: ["src"],
  });
  if (document.readyState === "loading") {
    window.addEventListener("DOMContentLoaded", () => refreshLegacyImagePlaceholders(document), { once: true });
  } else {
    refreshLegacyImagePlaceholders(document);
  }

  // Never attach privileged APIs to the site world.
  try {
    if ("aria" in window) {
      /* site must not receive app IPC; we never set window.aria here */
    }
  } catch {
    /* ignore */
  }

  const injectDesignStyle = () => {
    if (document.getElementById("aria-design-style")) return;
    const style = document.createElement("style");
    style.id = "aria-design-style";
    style.textContent =
      "*, *::before, *::after { cursor: default !important; }" +
      "[data-aria-inline-text] { cursor: text !important; outline: 2px solid var(--aria-composer-accent, #0f9f73) !important; outline-offset: 3px !important; border-radius: 2px; }" +
      "[data-aria-inline-status] { position: fixed; width: 1px; height: 1px; overflow: hidden; clip-path: inset(50%); white-space: nowrap; }";
    (document.head || document.documentElement)?.appendChild(style);
  };
  const removeDesignStyle = () => {
    document.getElementById("aria-design-style")?.remove();
  };

  const regions = new Map();
  let trackedPaths = [];
  let activeScope = "";
  let trackingRevision = 0;
  const inScope = (p) =>
    activeScope ? p.startsWith(activeScope) : !p.includes("|");
  let lastHoverPath = undefined;
  let lastHoverOcc = 0;
  let lastSelectedPath = null;
  let lastSelectedOccurrence = 0;
  let inlineTextRequestSequence = 0;
  let pendingInlineTextRequest = null;
  let activeInlineText = null;
  /** When false, immersive preview — links/forms work; selection chrome sleeps. */
  let designInteractive = true;
  let conditionBranches = [];

  const collectConditionBranches = () => {
    conditionBranches = conditionBranches.filter((branch) => branch.nodes.some((node) => node?.isConnected));
    for (const start of document.querySelectorAll("template[data-aria-condition-start]")) {
      const key = start.getAttribute("data-aria-condition-start");
      if (!key) continue;
      const nodes = [];
      let end = null;
      for (let node = start.nextSibling; node; node = node.nextSibling) {
        if (node.nodeType === 1 && node.tagName === "TEMPLATE" && node.getAttribute("data-aria-condition-end") === key) {
          end = node;
          break;
        }
        nodes.push(node);
      }
      if (!end) continue;
      conditionBranches.push({ nodes, active: start.getAttribute("data-aria-condition-active") === "true" });
      start.remove();
      end.remove();
    }
  };

  const setConditionNodeVisible = (node, visible, authoring) => {
    if (node.nodeType === 3) {
      if (!("__ariaConditionText" in node)) node.__ariaConditionText = node.nodeValue;
      node.nodeValue = visible ? node.__ariaConditionText : "";
      return;
    }
    if (node.nodeType !== 1 || node.tagName === "TEMPLATE") return;
    if (!("__ariaConditionDisplay" in node)) {
      node.__ariaConditionDisplay = [node.style.getPropertyValue("display"), node.style.getPropertyPriority("display")];
    }
    if (visible) {
      const saved = node.__ariaConditionDisplay || ["", ""];
      if (saved[0]) node.style.setProperty("display", saved[0], saved[1]);
      else node.style.removeProperty("display");
    } else {
      node.style.setProperty("display", "none", "important");
    }
    if (authoring && !node.__ariaConditionDecorated) {
      node.setAttribute("data-aria-condition-failed", "");
      node.__ariaConditionDecorated = true;
    } else if (!authoring && node.__ariaConditionDecorated) {
      node.removeAttribute("data-aria-condition-failed");
      node.__ariaConditionDecorated = false;
    }
  };

  const applyConditionBranches = () => {
    collectConditionBranches();
    for (const branch of conditionBranches) {
      for (const node of branch.nodes) {
        setConditionNodeVisible(node, designInteractive || branch.active, designInteractive && !branch.active);
      }
    }
  };

  const setDesignInteractive = (enabled) => {
    designInteractive = !!enabled;
    applyConditionBranches();
    if (designInteractive) {
      injectDesignStyle();
      return;
    }
    removeDesignStyle();
    if (lastHoverPath !== null && lastHoverPath !== undefined) {
      lastHoverPath = null;
      lastHoverOcc = 0;
      window.parent.postMessage(
        { type: MSG.hover, path: null, occurrence: 0 },
        "*",
      );
    }
  };

  if (document.readyState === "loading") {
    window.addEventListener("DOMContentLoaded", injectDesignStyle);
  } else {
    injectDesignStyle();
  }

  window.addEventListener(
    "click",
    (e) => {
      if (!designInteractive) return;
      const a =
        e.target instanceof Element ? e.target.closest("a[href]") : null;
      if (a) e.preventDefault();
    },
    true,
  );
  window.addEventListener(
    "submit",
    (e) => {
      if (!designInteractive) return;
      e.preventDefault();
    },
    true,
  );

  const collectRegions = () => {
    for (const [path, runs] of regions) {
      const connected = runs.filter((run) => run.some((node) => node?.isConnected));
      if (connected.length) regions.set(path, connected);
      else regions.delete(path);
    }
    const starts = document.querySelectorAll("template[" + MARKER_S + "]");
    for (const s of starts) {
      const p = s.getAttribute(MARKER_S);
      if (!p) continue;
      const run = [];
      const occurrence = (regions.get(p) || []).length;
      for (let n = s.nextSibling; n; n = n.nextSibling) {
        if (
          n.nodeType === 1 &&
          n.tagName === "TEMPLATE" &&
          n.getAttribute(MARKER_E) === p
        ) {
          break;
        }
        run.push(n);
        if (n.nodeType === 1 && n.tagName !== "TEMPLATE") {
          n.setAttribute(PATH_ATTR, p);
          n.setAttribute(OCCURRENCE_ATTR, String(occurrence));
        }
      }
      if (!regions.has(p)) regions.set(p, []);
      regions.get(p).push(run);
    }
    stripMarkers();
  };

  const liveRuns = (path, occurrence) => {
    const runs = (regions.get(path) || []).filter((run) =>
      run.some((node) => node && node.isConnected),
    );
    if (runs.length) {
      regions.set(path, runs);
      if (Number.isInteger(occurrence)) return runs[occurrence] ? [runs[occurrence]] : [];
      return runs;
    }
    const scopeBoundary = path.lastIndexOf("|") + 1;
    let cursor = path;
    const tail = [];
    while (cursor.lastIndexOf(".") >= scopeBoundary) {
      const separator = cursor.lastIndexOf(".");
      tail.unshift(cursor.slice(separator + 1));
      cursor = cursor.slice(0, separator);
      const ancestors = regions.get(cursor) || [];
      if (!ancestors.length || tail.some((part) => !/^\\d+$/.test(part))) continue;
      const resolved = ancestors.map((ancestorRun) => {
        let node = ancestorRun.find((candidate) => candidate.nodeType === 1) || ancestorRun[0];
        for (const part of tail) {
          const children = [...(node?.childNodes || [])].filter((child) =>
            !(child.nodeType === 1 && child.tagName === "TEMPLATE") &&
            !(child.nodeType === 3 && !child.textContent?.trim()),
          );
          node = children[Number(part)];
        }
        return node ? [node] : [];
      }).filter((run) => run.length);
      if (Number.isInteger(occurrence)) return resolved[occurrence] ? [resolved[occurrence]] : [];
      return resolved;
    }
    return [];
  };

  const firstElement = (run) => run.find((node) => node && node.nodeType === 1 && node.tagName !== "TEMPLATE");
  const motionSelector = ".aria-motion,.aria-parallax,[class*='aria-motion-'],[class*='aria-parallax-'],[data-aria-motion-duration-var],[data-aria-motion-delay-var],[data-aria-parallax-speed]";
  const elementUsesMotion = (element) => Boolean(
    element && (element.matches?.(motionSelector) || element.querySelector?.(motionSelector)),
  );
  const projectionUsesMotion = (node) => {
    if (!node || node.kind !== "element") return false;
    const attributes = node.attributes || {};
    if (Object.keys(attributes).some((name) => name.startsWith("data-aria-motion-") || name.startsWith("data-aria-parallax-"))) return true;
    if (typeof attributes.class === "string" && /(?:^|\\s)aria-(?:motion|parallax)(?:-|\\s|$)/.test(attributes.class)) return true;
    return (node.children || []).some(projectionUsesMotion);
  };

  const modelNodesById = new Map();
  const modelIdByNode = new WeakMap();
  const SVG_NS = "http://www.w3.org/2000/svg";
  const XLINK_NS = "http://www.w3.org/1999/xlink";
  let latestPatchRevision = 0;
  const projectedPaths = (nodes, output = []) => {
    for (const node of nodes || []) {
      if (!node || typeof node.path !== "string") continue;
      output.push(node.path);
      if (node.kind === "element") projectedPaths(node.children, output);
    }
    return output;
  };
  const projectedIds = (nodes, output = new Set()) => {
    for (const node of nodes || []) {
      if (!node || typeof node.id !== "string") continue;
      output.add(node.id);
      if (node.kind === "element") projectedIds(node.children, output);
    }
    return output;
  };
  const safeElementName = (tag) =>
    typeof tag === "string" && /^[A-Za-z][A-Za-z0-9]*$/.test(tag) &&
    !["base", "head", "html", "link", "meta", "noscript", "script", "style", "title"].includes(tag.toLowerCase());
  const isHydrationOwned = (node) =>
    node && node.nodeType === 1 && Boolean(node.closest?.("astro-island"));
  const concreteRun = (path, occurrence) =>
    (liveRuns(path, occurrence)[0] || []).filter((node) =>
      node && node.isConnected &&
      !(node.nodeType === 1 && node.tagName === "TEMPLATE") &&
      !(node.nodeType === 3 && !node.textContent?.trim()),
    );
  const nodeMatchesProjection = (projection, run) => {
    if (!projection || !run.length) return false;
    if (projection.kind === "opaque") return true;
    if (run.length !== 1 || isHydrationOwned(run[0])) return false;
    if (projection.kind === "text") return run[0].nodeType === 3;
    return run[0].nodeType === 1 && (
      run[0].namespaceURI === SVG_NS
        ? run[0].localName === projection.tagName
        : run[0].tagName.toLowerCase() === projection.tagName.toLowerCase()
    );
  };
  const occurrenceCount = (boundary) => {
    const first = boundary.before?.[0];
    if (first) return liveRuns(first.path).length;
    if (boundary.path === "$document") return 1;
    return liveRuns(boundary.path).length;
  };
  const preflightBoundary = (boundary) => {
    if (!boundary || !Array.isArray(boundary.before) || !Array.isArray(boundary.after)) {
      throw new Error("invalid-patch");
    }
    const occurrences = occurrenceCount(boundary);
    if (occurrences < 1) throw new Error("path-unavailable");
    for (let occurrence = 0; occurrence < occurrences; occurrence += 1) {
      const parent = boundary.path === "$document"
        ? document.body
        : firstElement(liveRuns(boundary.path, occurrence)[0] || []);
      if (!parent || isHydrationOwned(parent)) throw new Error("hydration-boundary");
      for (const projection of boundary.before) {
        const run = concreteRun(projection.path, occurrence);
        if (!nodeMatchesProjection(projection, run)) throw new Error("dom-shape-mismatch");
      }
      const validateAfter = (nodes) => {
        for (const node of nodes || []) {
          if (node.kind === "element") {
            if (!safeElementName(node.tagName)) throw new Error("unsafe-element");
            validateAfter(node.children);
          } else if (node.kind !== "text" && node.kind !== "opaque") {
            throw new Error("invalid-patch");
          }
        }
      };
      validateAfter(boundary.after);
    }
    return occurrences;
  };
  const rememberBeforeTree = (projection, occurrence) => {
    const run = concreteRun(projection.path, occurrence);
    modelNodesById.set(projection.id + "#" + occurrence, run);
    for (const node of run) modelIdByNode.set(node, projection.id);
    if (projection.kind === "element") {
      for (const child of projection.children || []) rememberBeforeTree(child, occurrence);
    }
  };
  const updateStaticAttributes = (element, before, after) => {
    const previous = before?.attributes || {};
    const next = after?.attributes || {};
    for (const name of Object.keys(previous)) {
      if (name in next || name === PATH_ATTR || /^on/i.test(name)) continue;
      if (name.startsWith("xlink:")) element.removeAttributeNS(XLINK_NS, name.slice(6));
      else element.removeAttribute(name);
    }
    for (const [name, value] of Object.entries(next)) {
      if (name === PATH_ATTR || /^on/i.test(name)) continue;
      if (name.startsWith("xlink:")) element.setAttributeNS(XLINK_NS, name, value);
      else element.setAttribute(name, value);
    }
  };
  const childNamespace = (parent, tagName) =>
    tagName === "svg" || (parent?.namespaceURI === SVG_NS && parent.tagName?.toLowerCase() !== "foreignobject")
      ? SVG_NS
      : "http://www.w3.org/1999/xhtml";
  const buildStaticNode = (projection, occurrence, beforeById, pathRuns, retainedIds, namespace) => {
    const remembered = modelNodesById.get(projection.id + "#" + occurrence) || [];
    const before = beforeById.get(projection.id);
    let nodes = remembered.filter(Boolean);
    if (projection.kind === "opaque") {
      if (!nodes.length) throw new Error("dom-shape-mismatch");
      pathRuns.set(projection.path, nodes);
      return nodes;
    }
    if (projection.kind === "text") {
      let text = nodes.length === 1 && nodes[0].nodeType === 3 ? nodes[0] : null;
      if (!text) text = document.createTextNode(projection.text);
      else if (text.textContent !== projection.text) text.textContent = projection.text;
      modelIdByNode.set(text, projection.id);
      nodes = [text];
      pathRuns.set(projection.path, nodes);
      return nodes;
    }
    let element = nodes.length === 1 && nodes[0].nodeType === 1 ? nodes[0] : null;
    const compatibleElement = element && (
      namespace === SVG_NS
        ? element.namespaceURI === SVG_NS && element.localName === projection.tagName
        : element.namespaceURI !== SVG_NS && element.tagName.toLowerCase() === projection.tagName.toLowerCase()
    );
    if (!compatibleElement) {
      const replacement = namespace === SVG_NS
        ? document.createElementNS(SVG_NS, projection.tagName)
        : document.createElement(projection.tagName);
      if (element) {
        for (const attribute of [...element.attributes]) replacement.setAttribute(attribute.name, attribute.value);
        while (element.firstChild) replacement.appendChild(element.firstChild);
        element.replaceWith(replacement);
      }
      element = replacement;
    }
    updateStaticAttributes(element, before, projection);
    element.setAttribute(PATH_ATTR, projection.path);
    modelIdByNode.set(element, projection.id);
    const childBefore = new Map((before?.children || []).map((child) => [child.id, child]));
    const knownBeforeNodes = (before?.children || []).flatMap((child) =>
      modelNodesById.get(child.id + "#" + occurrence) || [],
    );
    const position = document.createComment("aria-static-tree");
    const firstKnown = knownBeforeNodes.find((node) => node?.parentNode === element) || null;
    element.insertBefore(position, firstKnown);
    const childRuns = projection.children.flatMap((child) =>
      buildStaticNode(
        child, occurrence, childBefore, pathRuns, retainedIds,
        child.kind === "element" ? childNamespace(element, child.tagName) : element.namespaceURI,
      ),
    );
    let cursor = position;
    for (const node of childRuns) {
      if (node !== cursor.nextSibling) element.insertBefore(node, cursor.nextSibling);
      cursor = node;
    }
    position.remove();
    for (const child of before?.children || []) {
      if (retainedIds.has(child.id)) continue;
      for (const node of modelNodesById.get(child.id + "#" + occurrence) || []) node.remove();
    }
    nodes = [element];
    pathRuns.set(projection.path, nodes);
    return nodes;
  };
  const applyStaticBoundary = (boundary, occurrences) => {
    const oldPaths = projectedPaths(boundary.before);
    const retainedIds = projectedIds(boundary.after);
    const nextRuns = new Map();
    for (let occurrence = 0; occurrence < occurrences; occurrence += 1) {
      for (const projection of boundary.before) rememberBeforeTree(projection, occurrence);
      const parent = boundary.path === "$document"
        ? document.body
        : firstElement(liveRuns(boundary.path, occurrence)[0] || []);
      if (!parent) throw new Error("path-unavailable");
      const beforeById = new Map(boundary.before.map((node) => [node.id, node]));
      const occurrenceRuns = new Map();
      const knownBeforeNodes = boundary.before.flatMap((node) =>
        modelNodesById.get(node.id + "#" + occurrence) || [],
      );
      const position = document.createComment("aria-static-tree");
      const firstKnown = knownBeforeNodes.find((node) => node?.parentNode === parent) || null;
      parent.insertBefore(position, firstKnown);
      const afterRuns = boundary.after.flatMap((node) =>
        buildStaticNode(
          node, occurrence, beforeById, occurrenceRuns, retainedIds,
          node.kind === "element" ? childNamespace(parent, node.tagName) : parent.namespaceURI,
        ),
      );
      let cursor = position;
      for (const node of afterRuns) {
        if (node !== cursor.nextSibling) parent.insertBefore(node, cursor.nextSibling);
        cursor = node;
      }
      position.remove();
      for (const before of boundary.before) {
        if (retainedIds.has(before.id)) continue;
        for (const node of modelNodesById.get(before.id + "#" + occurrence) || []) node.remove();
      }
      for (const [path, run] of occurrenceRuns) {
        const list = nextRuns.get(path) || [];
        list[occurrence] = run;
        nextRuns.set(path, list);
      }
    }
    for (const path of oldPaths) regions.delete(path);
    for (const [path, runs] of nextRuns) regions.set(path, runs);
  };

  const patchNodes = (message) => {
    const revision = Number(message.revision);
    const paths = [...new Set((message.patches || []).flatMap((patch) =>
      patch?.kind === "properties" && typeof patch.path === "string"
        ? [patch.path]
        : patch?.kind === "static-tree" && Array.isArray(patch.boundaries)
          ? patch.boundaries.map((boundary) => boundary?.path).filter((path) => typeof path === "string")
          : [],
    ))];
    if (revision <= latestPatchRevision) {
      window.parent.postMessage({ type: MSG.patchResult, revision, status: "stale", paths, reason: "stale-revision" }, "*");
      return;
    }
    // Claim the revision before preflight. A rejected newer transaction still
    // makes every older message stale; applying it afterward would rewind DOM.
    latestPatchRevision = revision;
    try {
      const staticWork = [];
      let motionAffected = false;
      for (const patch of message.patches || []) {
        if (patch?.kind === "static-tree") {
          for (const boundary of patch.boundaries || []) {
            staticWork.push([boundary, preflightBoundary(boundary)]);
            motionAffected = motionAffected ||
              boundary.before.some(projectionUsesMotion) ||
              boundary.after.some(projectionUsesMotion) ||
              liveRuns(boundary.path).some((run) => elementUsesMotion(firstElement(run)));
          }
          continue;
        }
        if (!patch || patch.kind !== "properties" || typeof patch.path !== "string") throw new Error("invalid-patch");
        const runs = liveRuns(patch.path, patch.occurrence);
        if (!runs.length) throw new Error("path-unavailable");
        for (const run of runs) {
          const owned = run.some((node) => isHydrationOwned(node) || isHydrationOwned(node.parentElement));
          if (owned) throw new Error("hydration-boundary");
          if (patch.tagName != null && !safeElementName(String(patch.tagName).trim().toLowerCase())) {
            throw new Error("unsafe-element");
          }
          if (patch.attributes != null && (
            typeof patch.attributes !== "object" ||
            Object.entries(patch.attributes).some(([name, value]) =>
              name === PATH_ATTR || /^on/i.test(name) || (value !== null && typeof value !== "string"),
            )
          )) throw new Error("invalid-patch");
          motionAffected = motionAffected || elementUsesMotion(firstElement(run));
        }
        if (patch.attributes && Object.entries(patch.attributes).some(([name, value]) =>
          name.startsWith("data-aria-motion-") || name.startsWith("data-aria-parallax-") ||
          (name === "class" && typeof value === "string" && value.includes("aria-")),
        )) motionAffected = true;
      }
      for (const patch of message.patches || []) {
        if (patch.kind !== "properties") continue;
        const patchRuns = liveRuns(patch.path, patch.occurrence);
        for (let runIndex = 0; runIndex < patchRuns.length; runIndex += 1) {
          const run = patchRuns[runIndex];
          const origin = message.inlineTextOrigin;
          if (
            activeInlineText && origin &&
            origin.sessionId === activeInlineText.sessionId &&
            origin.path === patch.path &&
            origin.occurrence === activeInlineText.occurrence &&
            (patch.occurrence == null ? runIndex : patch.occurrence) === activeInlineText.occurrence
          ) continue;
          let element = firstElement(run);
          if (typeof patch.tagName === "string" && element) {
            const tag = patch.tagName.trim();
            if (!safeElementName(tag) || isHydrationOwned(element)) throw new Error("unsafe-element");
            const namespace = childNamespace(element.parentElement, tag);
            const replacement = namespace === SVG_NS
              ? document.createElementNS(SVG_NS, tag)
              : document.createElement(tag);
            for (const attribute of [...element.attributes]) {
              if (attribute.name.startsWith("xlink:")) {
                replacement.setAttributeNS(XLINK_NS, attribute.name, attribute.value);
              } else {
                replacement.setAttribute(attribute.name, attribute.value);
              }
            }
            while (element.firstChild) replacement.appendChild(element.firstChild);
            element.replaceWith(replacement);
            const index = run.indexOf(element);
            if (index >= 0) run[index] = replacement;
            element = replacement;
          }
          if (element && patch.attributes && typeof patch.attributes === "object") {
            for (const [name, value] of Object.entries(patch.attributes)) {
              if (name === PATH_ATTR || /^on/i.test(name)) continue;
              if (value === null) element.removeAttribute(name);
              else if (typeof value === "string") element.setAttribute(name, value);
            }
            element.setAttribute(PATH_ATTR, patch.path);
          }
          if (typeof patch.text === "string") {
            const text = run.find((node) => node && node.nodeType === 3) || null;
            if (text) text.textContent = patch.text;
            else if (element && !element.children.length) element.textContent = patch.text;
          }
        }
      }
      for (const [boundary, occurrences] of staticWork) applyStaticBoundary(boundary, occurrences);
      if (motionAffected) {
        try { window.AriaMotion?.init?.(); } catch {}
      }
      queueRects();
      diagnostics.patches += 1;
      window.parent.postMessage({ type: MSG.patchResult, revision, status: "applied", paths }, "*");
    } catch (error) {
      const reason = error instanceof Error && [
        "invalid-patch", "path-unavailable", "occurrence-mismatch", "dom-shape-mismatch",
        "hydration-boundary", "unsafe-element", "stale-revision",
      ].includes(error.message) ? error.message : "patch-exception";
      window.parent.postMessage({ type: MSG.patchResult, revision, status: "rejected", paths, reason }, "*");
    }
  };

  const executableAssets = (doc) => [
    ...[...doc.querySelectorAll("script")].map((node) =>
      "script:" + (node.getAttribute("type") || "") + ":" + (node.getAttribute("src") || "") + ":" + (node.src ? "" : node.textContent || ""),
    ),
    ...[...doc.querySelectorAll("head base, head link, head meta, head style, head title")]
      .filter((node) =>
        ![
          "aria-design-style",
          "aria-composer-preview-style",
          "aria-composer-display-style",
          "aria-transient-scrollbars",
        ].includes(node.id) &&
        !node.hasAttribute("data-aria-motion-asset") &&
        !node.hasAttribute("data-aria-composer-font-asset") &&
        !node.hasAttribute("data-vite-dev-id") &&
        !node.hasAttribute("data-vite-dev-css"),
      ).map((node) =>
      node.tagName.toLowerCase() + ":" + [...node.attributes].map((attribute) => attribute.name + "=" + attribute.value).sort().join(";") + ":" + (node.textContent || ""),
      ),
  ].sort();

  const nodeKey = (node) => {
    if (!node || node.nodeType !== 1) return "";
    const marker = node.getAttribute(MARKER_S) || node.getAttribute(MARKER_E);
    if (marker) return "marker:" + marker + ":" + (node.hasAttribute(MARKER_S) ? "s" : "e");
    const id = node.getAttribute("id");
    return id ? "id:" + id : "";
  };
  const islandSignature = (element) => [
    "component-url", "component-export", "renderer-url", "before-hydration-url",
    "props", "client", "opts",
  ].map((name) => name + "=" + (element.getAttribute(name) || "")).join("|");
  const morphState = new WeakMap();
  const captureMorphState = (root) => {
    const descendants = root.querySelectorAll ? [...root.querySelectorAll("*")] : [];
    const elements = [root, ...descendants];
    for (const element of elements) {
      const state = { scrollLeft: element.scrollLeft, scrollTop: element.scrollTop };
      if (element instanceof HTMLInputElement || element instanceof HTMLTextAreaElement) {
        state.value = element.value;
        state.dirtyValue = document.activeElement === element || element.value !== (element.getAttribute("value") || "");
        if (element instanceof HTMLInputElement) {
          state.checked = element.checked;
          state.dirtyChecked = element.checked !== element.defaultChecked;
        }
        if (document.activeElement === element && typeof element.selectionStart === "number") {
          state.selection = [element.selectionStart, element.selectionEnd, element.selectionDirection];
        }
      } else if (element instanceof HTMLSelectElement) {
        state.selected = [...element.selectedOptions].map((option) => option.value);
        state.dirtySelected = document.activeElement === element || [...element.options].some((option) => option.selected !== option.defaultSelected);
      }
      morphState.set(element, state);
    }
    return elements;
  };
  const restoreMorphState = (element) => {
    const state = morphState.get(element);
    if (!state) return;
    if (state.dirtyValue) element.value = state.value;
    if (state.dirtyChecked) element.checked = state.checked;
    if (state.dirtySelected) for (const option of element.options) option.selected = state.selected.includes(option.value);
    if (state.selection) try { element.setSelectionRange(...state.selection); } catch {}
    element.scrollLeft = state.scrollLeft;
    element.scrollTop = state.scrollTop;
  };
  const morphOptions = {
    getNodeKey: nodeKey,
    onBeforeElUpdated(current, incoming) {
      if (current.tagName === "ASTRO-ISLAND") {
        if (islandSignature(current) !== islandSignature(incoming)) throw new Error("hydration-boundary-changed");
        return false;
      }
      if (["VIDEO", "AUDIO", "IFRAME"].includes(current.tagName)) return false;
      return true;
    },
    onElUpdated: restoreMorphState,
  };
  const morphChildren = (currentParent, incomingParent) => {
    const activeElement = document.activeElement;
    const preservedElements = captureMorphState(currentParent);
    morphdom(currentParent, incomingParent, { ...morphOptions, childrenOnly: true });
    for (const element of preservedElements) if (element.isConnected) restoreMorphState(element);
    if (activeElement && activeElement.isConnected && document.activeElement !== activeElement) {
      try { activeElement.focus({ preventScroll: true }); } catch { try { activeElement.focus(); } catch {} }
      restoreMorphState(activeElement);
    }
  };
  const morphRun = (run, sourceRun) => {
    const parent = run[0]?.parentNode;
    if (!parent) throw new Error("marker-disconnected");
    const activeElement = document.activeElement;
    const activeSelection = activeElement && typeof activeElement.selectionStart === "number"
      ? [activeElement.selectionStart, activeElement.selectionEnd, activeElement.selectionDirection]
      : null;
    const container = document.createElement("aria-morph-root");
    container.style.display = "contents";
    parent.insertBefore(container, run[0]);
    for (const node of run) container.appendChild(node);
    const incoming = container.cloneNode(false);
    incoming.style.display = "contents";
    for (const node of sourceRun) incoming.appendChild(document.importNode(node, true));
    morphChildren(container, incoming);
    const output = [...container.childNodes];
    for (const node of output) parent.insertBefore(node, container);
    container.remove();
    if (activeElement && activeElement.isConnected && document.activeElement !== activeElement) {
      try { activeElement.focus({ preventScroll: true }); } catch { try { activeElement.focus(); } catch {} }
      restoreMorphState(activeElement);
      if (activeSelection) try { activeElement.setSelectionRange(...activeSelection); } catch {}
    }
    return output;
  };

  const responseRuns = (doc, path) => {
    const output = [];
    for (const start of doc.querySelectorAll("template[" + MARKER_S + "]")) {
      if (start.getAttribute(MARKER_S) !== path) continue;
      const run = [];
      for (let node = start.nextSibling; node; node = node.nextSibling) {
        if (node.nodeType === 1 && node.tagName === "TEMPLATE" && node.getAttribute(MARKER_E) === path) break;
        run.push(node);
      }
      output.push(run);
    }
    return output;
  };

  let latestReconcileRevision = 0;
  let reconcileAbort = null;
  const reconcileRevision = async (revision, paths, attempt = 0) => {
    if (revision < latestReconcileRevision) return;
    latestReconcileRevision = revision;
    const scrollX = window.scrollX;
    const scrollY = window.scrollY;
    if (reconcileAbort) reconcileAbort.abort();
    const abort = new AbortController();
    reconcileAbort = abort;
    try {
      const response = await fetch(location.href, { signal: abort.signal, cache: "no-store", headers: { "x-aria-composer-revision": String(revision) } });
      if (!response.ok) throw new Error("preview-fetch-" + response.status);
      const parsed = new DOMParser().parseFromString(await response.text(), "text/html");
      if (revision < latestReconcileRevision) return;
      if (JSON.stringify(executableAssets(document)) !== JSON.stringify(executableAssets(parsed))) {
        diagnostics.reloadReasons["executable-assets-changed"] = (diagnostics.reloadReasons["executable-assets-changed"] || 0) + 1;
        window.parent.postMessage({ type: MSG.reconcileResult, revision, ok: false, status: "reload-required", paths, reason: "executable-assets-changed", hardReload: true }, "*");
        return;
      }
      for (const path of paths) {
        if (path === "$document") {
          if (parsed.body.querySelector("script")) throw new Error("unsupported-executable-fragment");
          morphChildren(document.body, parsed.body);
          regions.clear();
          collectRegions();
          applyConditionBranches();
          continue;
        }
        const current = liveRuns(path);
        const incoming = responseRuns(parsed, path);
        if (!current.length || current.length !== incoming.length) throw new Error("marker-occurrence-mismatch:" + path);
        current.forEach((run, occurrence) => {
          const sourceRun = incoming[occurrence] || [];
          if (sourceRun.some((node) => node.nodeType === 1 && (node.tagName === "SCRIPT" || node.querySelector?.("script")))) {
            throw new Error("unsupported-executable-fragment");
          }
          const inserted = morphRun(run, sourceRun);
          for (const node of inserted) {
            if (node.nodeType === 1 && node.tagName !== "TEMPLATE") node.setAttribute(PATH_ATTR, path);
          }
          regions.set(path, (regions.get(path) || []).map((old, index) => index === occurrence ? inserted : old));
        });
      }
      collectRegions();
      applyConditionBranches();
      try { window.AriaMotion?.init?.(); } catch {}
      window.scrollTo(scrollX, scrollY);
      queueRects();
      await Promise.all([...document.querySelectorAll('link[rel="stylesheet"]')].map((link) => link.sheet ? Promise.resolve() : new Promise((resolve) => {
        link.addEventListener("load", resolve, { once: true });
        link.addEventListener("error", resolve, { once: true });
      })));
      if (revision < latestReconcileRevision || abort.signal.aborted) return;
      diagnostics.morphs += 1;
      window.parent.postMessage({ type: MSG.reconcileResult, revision, ok: true, status: "morphed", paths }, "*");
    } catch (error) {
      if (abort.signal.aborted) return;
      if (revision < latestReconcileRevision) return;
      if (attempt < 1) {
        nextFrame(() => void reconcileRevision(revision, paths, attempt + 1));
        return;
      }
      window.scrollTo(scrollX, scrollY);
      const detail = error instanceof Error ? error.message : String(error);
      const reason = detail.startsWith("hydration-")
        ? "hydration-ownership-changed"
        : detail.startsWith("marker-")
          ? "markers-irrecoverable"
          : "reconciliation-failed";
      diagnostics.reloadReasons[reason] = (diagnostics.reloadReasons[reason] || 0) + 1;
      window.parent.postMessage({
        type: MSG.reconcileResult, revision, ok: false, paths,
        status: "reload-required", reason, detail, hardReload: true,
      }, "*");
    }
  };

  const pendingReconciles = new Map();
  let latestSourceReadyRevision = 0;
  const reconcileReadyRevision = (revision) => {
    // The draft store may advance a requested revision when an older draft is
    // still present (notably across page navigation). A ready revision covers
    // every pending mutation at or below it; requiring an exact key strands
    // those DOM changes until unrelated HMR reloads the page.
    const covered = [...pendingReconciles.entries()]
      .filter(([key]) => key <= revision)
      .sort(([a], [b]) => a - b);
    if (!covered.length) {
      window.parent.postMessage({ type: MSG.reconcileResult, revision, ok: true, status: "patched", paths: [] }, "*");
      return;
    }
    const candidates = [...new Set(covered.flatMap(([, value]) => value.paths))]
      .sort((a, b) => a.split(".").length - b.split(".").length || a.localeCompare(b));
    const paths = candidates.filter((path) =>
      !candidates.some((parent) => parent !== path && (parent === "$document" || path.startsWith(parent + "."))),
    );
    for (const [key] of covered) pendingReconciles.delete(key);
    const reloadReason = [...covered].reverse().find(([, value]) => value.reloadReason)?.[1].reloadReason;
    if (reloadReason) {
      if (revision < latestReconcileRevision) return;
      latestReconcileRevision = revision;
      diagnostics.reloadReasons[reloadReason] = (diagnostics.reloadReasons[reloadReason] || 0) + 1;
      window.parent.postMessage({
        type: MSG.reconcileResult, revision, ok: false, paths,
        status: "reload-required", reason: reloadReason, hardReload: true,
      }, "*");
      return;
    }
    void reconcileRevision(revision, paths);
  };
  window.addEventListener("aria:source-ready", (event) => {
    const payload = event && event.detail;
    const revision = payload && Number(payload.revision);
    if (!Number.isFinite(revision)) return;
    diagnostics.preventedFullReloads += 1;
    latestSourceReadyRevision = Math.max(latestSourceReadyRevision, revision);
    reconcileReadyRevision(revision);
  });

  const addNode = (acc, n) => {
    if (!n.isConnected) return acc;
    let b = null;
    if (n.nodeType === 1) {
      if (n.tagName === "TEMPLATE") return acc;
      b = n.getBoundingClientRect();
      if (b.width === 0 && b.height === 0) {
        for (const c of n.childNodes) acc = addNode(acc, c);
        return acc;
      }
    } else if (n.nodeType === 3 && n.textContent && n.textContent.trim()) {
      const range = document.createRange();
      range.selectNode(n);
      b = range.getBoundingClientRect();
    }
    if (!b || (b.width === 0 && b.height === 0)) return acc;
    if (!acc) return { left: b.left, top: b.top, right: b.right, bottom: b.bottom };
    return {
      left: Math.min(acc.left, b.left),
      top: Math.min(acc.top, b.top),
      right: Math.max(acc.right, b.right),
      bottom: Math.max(acc.bottom, b.bottom),
    };
  };

  const toRect = (a) => ({
    x: a.left,
    y: a.top,
    w: a.right - a.left,
    h: a.bottom - a.top,
  });

  const rectsFromDescendants = (p) => {
    const prefix = p + ".";
    let best = Infinity;
    const paths = [];
    for (const key of regions.keys()) {
      if (!key.startsWith(prefix)) continue;
      const depth = key.split(".").length;
      if (depth < best) {
        best = depth;
        paths.length = 0;
      }
      if (depth === best) paths.push(key);
    }
    let acc = null;
    for (const key of paths) {
      for (const run of regions.get(key) || []) {
        for (const n of run) acc = addNode(acc, n);
      }
    }
    return acc ? [toRect(acc)] : null;
  };

  const rectsFromRegion = (p) => {
    const runs = (regions.get(p) || []).filter((run) =>
      run.some((node) => node?.isConnected),
    );
    if (runs.length) regions.set(p, runs);
    else regions.delete(p);

    // Group by the occurrence stamped during marker collection. This keeps
    // multi-root components together and repeated instances separate even if
    // reconciliation replaced a run and the in-memory array is incomplete.
    const byOccurrence = new Map();
    const countedElements = new Set();
    for (let index = 0; index < runs.length; index += 1) {
      const run = runs[index];
      const stampedOccurrence = Number.parseInt(
        firstElement(run)?.getAttribute(OCCURRENCE_ATTR) || "",
        10,
      );
      const occurrence = Number.isInteger(stampedOccurrence)
        ? stampedOccurrence
        : index;
      let acc = null;
      for (const n of run) {
        acc = addNode(acc, n);
        if (n?.nodeType === 1) countedElements.add(n);
      }
      if (acc) byOccurrence.set(occurrence, acc);
    }

    // Marker runs are an optimization, not the source of truth. Reconciliation
    // or late DOM ownership can leave a connected stamped node without a live
    // entry in the private map. Recover exact geometry from the DOM so opening
    // a component never depends on whether that map has already seen it.
    let fallbackOccurrence = byOccurrence.size
      ? Math.max(...byOccurrence.keys()) + 1
      : 0;
    for (const el of document.querySelectorAll(
      "[" + PATH_ATTR + '="' + CSS.escape(p) + '"]',
    )) {
      if (!el.isConnected) continue;
      if (countedElements.has(el)) continue;
      const stampedOccurrence = Number.parseInt(
        el.getAttribute(OCCURRENCE_ATTR) || "",
        10,
      );
      const occurrence = Number.isInteger(stampedOccurrence)
        ? stampedOccurrence
        : fallbackOccurrence++;
      byOccurrence.set(
        occurrence,
        addNode(byOccurrence.get(occurrence) || null, el),
      );
    }
    const recovered = [...byOccurrence.entries()]
      .sort(([a], [b]) => a - b)
      .map(([, acc]) => acc && toRect(acc))
      .filter(Boolean);
    return recovered.length ? recovered : null;
  };

  const rectsFromAncestors = (p) => {
    // Inline runs are intentionally serialized without nested marker templates
    // so their whitespace and phrasing layout stay intact. Keep the exact child
    // path selected, but use its nearest marked ancestor for canvas feedback.
    const scopeBoundary = p.lastIndexOf("|") + 1;
    let cursor = p;
    while (cursor.lastIndexOf(".") >= scopeBoundary) {
      cursor = cursor.slice(0, cursor.lastIndexOf("."));
      const rects = rectsFromRegion(cursor);
      if (rects && rects.length) return rects;
    }
    return null;
  };

  const rectsForPath = (p) => {
    return (
      rectsFromRegion(p) ||
      rectsFromDescendants(p) ||
      rectsFromAncestors(p)
    );
  };

  const classesForPath = (p) => {
    const out = [];
    for (const run of regions.get(p) || []) {
      const el = run.find((n) => n.nodeType === 1 && n.tagName !== "TEMPLATE");
      if (el) out.push([...el.classList]);
    }
    if (!out.length) {
      for (const el of document.querySelectorAll(
        "[" + PATH_ATTR + '="' + CSS.escape(p) + '"]',
      )) {
        out.push([...el.classList]);
      }
    }
    return out;
  };

  const ownerChainsForPath = (p) => {
    const runs = regions.get(p) || [];
    return runs.map((run, occurrence) => {
      const first = run.find((n) => n && n.nodeType === 1);
      const chain = [];
      let el = first && first.parentElement;
      while (el) {
        const owner = el.getAttribute && el.getAttribute(PATH_ATTR);
        if (owner && owner !== p) chain.unshift(owner);
        el = el.parentElement;
      }
      chain.push(p + "#" + occurrence);
      return chain;
    });
  };

  const sendRects = () => {
    if (!trackedPaths.length) return;
    const rects = {};
    const classes = {};
    const owners = {};
    for (const p of trackedPaths) {
      rects[p] = rectsForPath(p);
      classes[p] = classesForPath(p);
      owners[p] = ownerChainsForPath(p);
    }
    window.parent.postMessage({
      type: MSG.rects,
      trackingRevision,
      rects,
      classes,
      owners,
    }, "*");
  };

  const SCROLL_MARGIN = 24;
  const scrollElementForPath = (p, occ) => {
    const scopeBoundary = p.lastIndexOf("|") + 1;
    let cursor = p;
    while (cursor) {
      const runs = regions.get(cursor);
      const run = runs && (runs[occ] || runs[0]);
      if (run) {
        for (const node of run) {
          if (node.nodeType === 1) return node;
          if (node.nodeType === 3 && node.parentElement) return node.parentElement;
        }
      }
      const separator = cursor.lastIndexOf(".");
      if (separator < scopeBoundary) break;
      cursor = cursor.slice(0, separator);
    }
    return null;
  };

  const scrollPathIntoView = (p, occ, policy) => {
    const rects = rectsForPath(p);
    if (!rects || !rects.length) return;
    const r = rects[occ] || rects[0];
    const vh = window.innerHeight || document.documentElement.clientHeight;
    const vw = window.innerWidth || document.documentElement.clientWidth;
    const fullyVisible =
      r.y >= SCROLL_MARGIN &&
      r.y + r.h <= vh - SCROLL_MARGIN &&
      r.x >= SCROLL_MARGIN &&
      r.x + r.w <= vw - SCROLL_MARGIN;
    if (policy !== "center" && fullyVisible) return;
    const element = scrollElementForPath(p, occ);
    if (element) {
      element.scrollIntoView({
        behavior: "auto",
        block: policy === "center" ? "center" : "nearest",
        inline: "nearest",
      });
      return;
    }
    const targetTop = policy === "center"
      ? window.scrollY + r.y - (r.h >= vh - SCROLL_MARGIN * 2
        ? SCROLL_MARGIN
        : (vh - r.h) / 2)
      : window.scrollY + (
        r.y < SCROLL_MARGIN
          ? r.y - SCROLL_MARGIN
          : Math.max(0, r.y + r.h - (vh - SCROLL_MARGIN))
      );
    window.scrollTo({
      top: Math.max(0, targetTop),
      behavior: "auto",
    });
  };

  let viewportQueued = false;
  const sendViewport = () => {
    viewportQueued = false;
    window.parent.postMessage(
      {
        type: MSG.viewport,
        href: location.href,
        x: window.scrollX,
        y: window.scrollY,
      },
      "*",
    );
  };
  const queueViewport = () => {
    if (viewportQueued) return;
    viewportQueued = true;
    nextFrame(sendViewport);
  };
  const restoreViewport = (x, y) => {
    const root = document.documentElement;
    const previous = root.style.scrollBehavior;
    root.style.scrollBehavior = "auto";
    window.scrollTo(Math.max(0, x), Math.max(0, y));
    root.style.scrollBehavior = previous;
    queueRects();
  };

  let rectsQueued = false;
  let regionsDirty = false;
  const queueRects = () => {
    if (rectsQueued) return;
    rectsQueued = true;
    nextFrame(() => {
      rectsQueued = false;
      if (regionsDirty) {
        regionsDirty = false;
        collectRegions();
      }
      sendRects();
    });
  };

  const occurrenceOf = (path, target) => {
    const runs = regions.get(path);
    if (!runs || runs.length < 2) return 0;
    for (let i = 0; i < runs.length; i++) {
      for (const n of runs[i]) {
        if (!n.isConnected) continue;
        if (n === target || (n.nodeType === 1 && n.contains(target))) return i;
      }
    }
    return 0;
  };

  const inlineStatus = () => {
    let status = document.querySelector("[data-aria-inline-status]");
    if (!status) {
      status = document.createElement("span");
      status.setAttribute("data-aria-inline-status", "");
      status.setAttribute("role", "status");
      status.setAttribute("aria-live", "polite");
      (document.body || document.documentElement).appendChild(status);
    }
    return status;
  };
  const announceInline = (message) => {
    const status = inlineStatus();
    status.textContent = "";
    setTimeout(() => { status.textContent = message; }, 0);
  };
  const inlineRunValue = (path, occurrence) =>
    (liveRuns(path, occurrence)[0] || []).map((node) => node.textContent || "").join("");
  const clearPendingInlineText = (reason, notifyHost = true) => {
    const pending = pendingInlineTextRequest;
    if (!pending) return;
    pending.imeCapture?.remove();
    pendingInlineTextRequest = null;
    if (notifyHost) {
      window.parent.postMessage({
        type: MSG.inlineTextStartResult,
        requestId: pending.requestId,
        ok: false,
        ...(reason ? { reason } : {}),
      }, "*");
    }
  };
  const requestInlineText = (mode, initialInput) => {
    if (!lastSelectedPath || activeInlineText || pendingInlineTextRequest) return;
    const requestId = "inline-request-" + (++inlineTextRequestSequence);
    pendingInlineTextRequest = {
      requestId,
      path: lastSelectedPath,
      occurrence: lastSelectedOccurrence,
      initialInput,
      imeCapture: null,
      imeValue: null,
      startMessage: null,
    };
    window.parent.postMessage({
      type: MSG.inlineTextRequest,
      requestId,
      path: lastSelectedPath,
      occurrence: lastSelectedOccurrence,
      mode,
      ...(typeof initialInput === "string" ? { initialInput } : {}),
      renderedValue: inlineRunValue(lastSelectedPath, lastSelectedOccurrence),
    }, "*");
  };
  const requestInlineTextFromIme = () => {
    requestInlineText("replace");
    const pending = pendingInlineTextRequest;
    if (!pending) return;
    const capture = document.createElement("textarea");
    capture.setAttribute("aria-label", "Canvas text input");
    capture.setAttribute("tabindex", "-1");
    capture.setAttribute("autocomplete", "off");
    capture.setAttribute("autocapitalize", "off");
    capture.setAttribute("spellcheck", "false");
    capture.style.cssText = "position:fixed;left:-10000px;top:0;width:1px;height:1px;opacity:0;pointer-events:none";
    (document.body || document.documentElement).appendChild(capture);
    pending.imeCapture = capture;
    capture.focus({ preventScroll: true });
  };
  const inlineValue = (session) =>
    String(session.element.textContent || "")
      .replace(/\\r\\n?/g, "\\n")
      .replace(/[\\n\\u2028\\u2029]+/g, " ");
  const placeInlineCaret = (element, selectAll = false) => {
    const selection = window.getSelection();
    if (!selection) return;
    const range = document.createRange();
    range.selectNodeContents(element);
    if (!selectAll) range.collapse(false);
    selection.removeAllRanges();
    selection.addRange(range);
  };
  const sendInlineChange = () => {
    const session = activeInlineText;
    if (!session || session.composing || session.finishing) return;
    const value = inlineValue(session);
    if (session.element.textContent !== value) {
      session.element.textContent = value;
      placeInlineCaret(session.element);
    }
    for (const path of session.mirrorPaths) {
      for (const run of liveRuns(path)) {
        const text = run.find((node) => node?.nodeType === 3) || null;
        const mirror = text?.parentElement || firstElement(run);
        if (mirror && mirror !== session.element && !isHydrationOwned(mirror)) {
          mirror.textContent = value;
        }
      }
    }
    session.sequence += 1;
    window.parent.postMessage({
      type: MSG.inlineTextChange,
      sessionId: session.sessionId,
      path: session.path,
      occurrence: session.occurrence,
      sequence: session.sequence,
      value,
    }, "*");
  };
  const finishInlineText = (action) => {
    const session = activeInlineText;
    if (!session || session.finishing) return;
    session.finishing = true;
    session.sequence += 1;
    window.parent.postMessage({
      type: MSG.inlineTextFinish,
      sessionId: session.sessionId,
      path: session.path,
      occurrence: session.occurrence,
      sequence: session.sequence,
      value: inlineValue(session),
      action,
    }, "*");
  };
  const closeInlineText = (value, announcement) => {
    const session = activeInlineText;
    if (!session) return;
    session.element.textContent = value;
    session.element.removeAttribute("data-aria-inline-text");
    if (session.hadContenteditable) session.element.setAttribute("contenteditable", session.contenteditable);
    else session.element.removeAttribute("contenteditable");
    if (session.hadSpellcheck) session.element.setAttribute("spellcheck", session.spellcheck);
    else session.element.removeAttribute("spellcheck");
    if (session.hadTabindex) session.element.setAttribute("tabindex", session.tabindex);
    else session.element.removeAttribute("tabindex");
    activeInlineText = null;
    announceInline(announcement);
    queueRects();
  };
  const startInlineText = (message) => {
    const pending = pendingInlineTextRequest;
    if (
      activeInlineText || !pending || typeof message.path !== "string" ||
      message.requestId !== pending.requestId || message.occurrence !== pending.occurrence
    ) {
      window.parent.postMessage({
        type: MSG.inlineTextStartResult,
        requestId: message.requestId,
        sessionId: message.sessionId,
        ok: false,
        reason: "This canvas text request is no longer active.",
      }, "*");
      return;
    }
    if (pending.imeCapture && pending.imeValue === null) {
      pending.startMessage = message;
      return;
    }
    const run = liveRuns(message.path, message.occurrence)[0];
    const text = run?.find((node) => node?.nodeType === 3) || null;
    const element = text?.parentElement || firstElement(run || []);
    if (!element || isHydrationOwned(element)) {
      clearPendingInlineText("The selected text is no longer editable.", false);
      window.parent.postMessage({
        type: MSG.inlineTextStartResult,
        requestId: message.requestId,
        sessionId: message.sessionId,
        ok: false,
        reason: "The selected text is no longer editable.",
      }, "*");
      announceInline("The selected text is no longer editable.");
      return;
    }
    const hadTabindex = element.hasAttribute("tabindex");
    const hadContenteditable = element.hasAttribute("contenteditable");
    const hadSpellcheck = element.hasAttribute("spellcheck");
    const initialInput = typeof pending.imeValue === "string"
      ? pending.imeValue
      : (typeof message.initialInput === "string" ? message.initialInput : undefined);
    pending.imeCapture?.remove();
    pendingInlineTextRequest = null;
    activeInlineText = {
      sessionId: message.sessionId,
      path: message.path,
      occurrence: message.occurrence,
      mirrorPaths: Array.isArray(message.mirrorPaths)
        ? message.mirrorPaths.filter((path) => typeof path === "string")
        : [message.path],
      element,
      originalValue: message.value,
      sequence: 0,
      composing: false,
      finishing: false,
      hadTabindex,
      tabindex: element.getAttribute("tabindex") || "",
      hadContenteditable,
      contenteditable: element.getAttribute("contenteditable") || "",
      hadSpellcheck,
      spellcheck: element.getAttribute("spellcheck") || "",
    };
    element.setAttribute("data-aria-inline-text", "");
    element.setAttribute("contenteditable", "plaintext-only");
    element.setAttribute("spellcheck", "true");
    element.setAttribute("tabindex", "-1");
    element.textContent = typeof initialInput === "string"
      ? initialInput
      : message.value;
    element.focus({ preventScroll: true });
    placeInlineCaret(element, false);
    announceInline("Editing text on canvas.");
    window.parent.postMessage({
      type: MSG.inlineTextStartResult,
      requestId: message.requestId,
      sessionId: message.sessionId,
      ok: true,
    }, "*");
    if (typeof initialInput === "string") sendInlineChange();
  };

  const rectContainsPoint = (rect, x, y) => Boolean(
    rect && Number.isFinite(x) && Number.isFinite(y) &&
    x >= rect.left && x <= rect.right && y >= rect.top && y <= rect.bottom &&
    (rect.width > 0 || rect.height > 0)
  );

  const nodeContainsHit = (node, target, x, y) => {
    if (!node?.isConnected) return false;
    if (node.nodeType === 1) {
      if (node === target || node.contains(target)) return true;
      return rectContainsPoint(node.getBoundingClientRect(), x, y);
    }
    if (node.nodeType !== 3 || !node.textContent?.trim()) return false;
    const range = document.createRange();
    range.selectNode(node);
    const rects = typeof range.getClientRects === "function"
      ? [...range.getClientRects()]
      : [range.getBoundingClientRect()];
    return rects.some((rect) => rectContainsPoint(rect, x, y));
  };

  const nodeAt = (target, x, y) => {
    if (!(target instanceof Node)) return { path: null, occurrence: 0 };
    let tagged =
      target instanceof Element ? target.closest("[" + PATH_ATTR + "]") : null;
    while (tagged && !inScope(tagged.getAttribute(PATH_ATTR))) {
      tagged = tagged.parentElement
        ? tagged.parentElement.closest("[" + PATH_ATTR + "]")
        : null;
    }
    let best = tagged ? tagged.getAttribute(PATH_ATTR) : null;
    let bestDepth = best ? best.split(".").length : -1;
    let bestOccurrence = best ? occurrenceOf(best, target) : 0;
    for (const [p, runs] of regions) {
      if (!inScope(p)) continue;
      const depth = p.split(".").length;
      if (depth <= bestDepth) continue;
      for (let occurrence = 0; occurrence < runs.length; occurrence += 1) {
        const run = runs[occurrence];
        if (run.some((node) => nodeContainsHit(node, target, x, y))) {
          best = p;
          bestDepth = depth;
          bestOccurrence = occurrence;
          break;
        }
      }
    }
    return { path: best, occurrence: best ? bestOccurrence : 0 };
  };

  const targetAt = (e) =>
    (e.clientX || e.clientY
      ? document.elementFromPoint(e.clientX, e.clientY)
      : null) || e.target;

  const startOutlines = () => {
    collectRegions();
    applyConditionBranches();
    if (!regions.size) {
      try {
        window.parent.postMessage(
          {
            type: MSG.hover,
            path: null,
            occurrence: 0,
            warn: "no-markers",
          },
          "*",
        );
      } catch {
        /* ignore */
      }
      return;
    }
    window.addEventListener("scroll", queueRects, true);
    window.addEventListener("resize", queueRects);
    new MutationObserver((records) => {
      const hasStructuralMutation = records.some((record) =>
        record.type === "childList" && (
          record.addedNodes.length ||
          [...record.removedNodes].some((node) =>
            node.nodeType !== 1 ||
            node.tagName !== "TEMPLATE" ||
            (!node.hasAttribute(MARKER_S) && !node.hasAttribute(MARKER_E))
          )
        )
      );
      const hasMeaningfulMutation = records.some((record) => {
        if (record.type === "attributes") {
          return record.attributeName !== PATH_ATTR &&
            record.attributeName !== OCCURRENCE_ATTR;
        }
        if (record.type === "characterData") return true;
        return hasStructuralMutation;
      });
      if (!hasMeaningfulMutation) return;
      if (hasStructuralMutation) {
        regionsDirty = true;
      }
      queueRects();
    }).observe(
      document.body || document.documentElement,
      {
        childList: true,
        subtree: true,
        attributes: true,
        characterData: true,
      },
    );
    if (typeof ResizeObserver === "function") {
      const observer = new ResizeObserver(queueRects);
      observer.observe(document.documentElement);
    }
    document.addEventListener("load", queueRects, true);
    if (document.fonts?.ready) {
      document.fonts.ready.then(queueRects).catch(() => {});
    }
    document.addEventListener("mousemove", (e) => {
      if (!designInteractive) return;
      const { path: p, occurrence } = nodeAt(targetAt(e), e.clientX, e.clientY);
      if (p !== lastHoverPath || occurrence !== lastHoverOcc) {
        lastHoverPath = p;
        lastHoverOcc = occurrence;
        window.parent.postMessage(
          { type: MSG.hover, path: p, occurrence },
          "*",
        );
      }
    });
    document.documentElement.addEventListener("mouseleave", () => {
      if (!designInteractive) return;
      if (lastHoverPath !== null) {
        lastHoverPath = null;
        window.parent.postMessage(
          { type: MSG.hover, path: null, occurrence: 0 },
          "*",
        );
      }
    });
    document.addEventListener(
      "click",
      (e) => {
        if (!designInteractive) return;
        if (pendingInlineTextRequest) {
          clearPendingInlineText("Canvas text editing was canceled.");
        }
        if (activeInlineText) {
          if (activeInlineText.element.contains(e.target)) return;
          e.preventDefault();
          e.stopPropagation();
          finishInlineText("commit");
          return;
        }
        e.preventDefault();
        e.stopPropagation();
        const { path: p, occurrence } = nodeAt(targetAt(e), e.clientX, e.clientY);
        lastSelectedPath = p || null;
        lastSelectedOccurrence = occurrence;
        window.parent.postMessage(
          {
            type: MSG.click,
            path: p || null,
            occurrence,
            shift: !!e.shiftKey,
            meta: !!(e.metaKey || e.ctrlKey),
          },
          "*",
        );
      },
      true,
    );
    // Double-click drills into a component/layout (host opens that .astro).
    document.addEventListener(
      "dblclick",
      (e) => {
        if (!designInteractive) return;
        if (pendingInlineTextRequest) {
          clearPendingInlineText("Canvas text editing was canceled.");
          return;
        }
        if (activeInlineText) return;
        e.preventDefault();
        e.stopPropagation();
        const { path: p, occurrence } = nodeAt(targetAt(e), e.clientX, e.clientY);
        if (!p) return;
        window.parent.postMessage(
          { type: MSG.open, path: p, occurrence },
          "*",
        );
      },
      true,
    );
    // Forward edit chords when the canvas has focus (Stacki pattern).
    window.addEventListener(
      "keydown",
      (e) => {
        if (!designInteractive) return;
        if (activeInlineText) {
          if (e.key === "Escape") {
            e.preventDefault();
            e.stopPropagation();
            finishInlineText("cancel");
          } else if (e.key === "Enter") {
            e.preventDefault();
            e.stopPropagation();
            finishInlineText("commit");
          } else if (e.key === "Tab") {
            finishInlineText("commit");
          }
          return;
        }
        if (pendingInlineTextRequest) {
          if (e.key === "Escape") {
            e.preventDefault();
            e.stopPropagation();
            clearPendingInlineText("Canvas text editing was canceled.");
            announceInline("Text edit canceled.");
          }
          return;
        }
        if (isEditableTarget(e.target)) return;
        const mod = e.metaKey || e.ctrlKey;
        const startsIme = !mod && !e.altKey &&
          (e.key === "Process" || e.key === "Unidentified" || e.key === "Dead" || e.keyCode === 229);
        const startsExisting = !mod && !e.altKey && (e.key === "Enter" || e.key === "F2");
        const startsReplacement = !mod && !e.altKey && e.key.length === 1;
        if (startsIme) {
          e.stopPropagation();
          requestInlineTextFromIme();
          return;
        }
        if (startsExisting || startsReplacement) {
          e.preventDefault();
          e.stopPropagation();
          requestInlineText(startsReplacement ? "replace" : "edit", startsReplacement ? e.key : undefined);
          return;
        }
        const isUndoRedo =
          mod &&
          (e.key.toLowerCase() === "z" || e.key.toLowerCase() === "y");
        const isDuplicate =
          mod && !e.altKey && !e.shiftKey && e.key.toLowerCase() === "d";
        const isClipboard =
          mod && !e.altKey && ["c", "x", "v"].includes(e.key.toLowerCase());
        const isDelete =
          !mod &&
          !e.altKey &&
          (e.key === "Delete" || e.key === "Backspace");
        if (!isUndoRedo && !isDuplicate && !isDelete && !isClipboard) return;
        e.preventDefault();
        e.stopPropagation();
        window.parent.postMessage(
          {
            type: MSG.shortcut,
            key: e.key,
            meta: mod,
            shift: !!e.shiftKey,
          },
          "*",
        );
      },
      true,
    );

    const isEditableTarget = (target) =>
      target instanceof Element &&
      !!target.closest("input, textarea, select, [contenteditable]:not([contenteditable='false'])");
    document.addEventListener("input", (e) => {
      if (activeInlineText?.element.contains(e.target) && !activeInlineText.composing) sendInlineChange();
    }, true);
    document.addEventListener("compositionstart", (e) => {
      if (activeInlineText?.element.contains(e.target)) activeInlineText.composing = true;
    }, true);
    document.addEventListener("compositionend", (e) => {
      const pending = pendingInlineTextRequest;
      if (pending?.imeCapture === e.target) {
        pending.imeValue = String(pending.imeCapture.value || e.data || "")
          .replace(/\\r\\n?/g, "\\n")
          .replace(/[\\n\\u2028\\u2029]+/g, " ");
        pending.imeCapture.remove();
        pending.imeCapture = null;
        const startMessage = pending.startMessage;
        pending.startMessage = null;
        if (startMessage) startInlineText(startMessage);
        return;
      }
      if (!activeInlineText?.element.contains(e.target)) return;
      activeInlineText.composing = false;
      sendInlineChange();
    }, true);
    document.addEventListener("blur", (e) => {
      if (activeInlineText?.element === e.target) finishInlineText("commit");
    }, true);
    window.addEventListener(
      "paste",
      (e) => {
        if (activeInlineText?.element.contains(e.target)) {
          const text = (e.clipboardData?.getData("text/plain") || "")
            .replace(/\\r\\n?/g, "\\n").replace(/[\\n\\u2028\\u2029]+/g, " ");
          e.preventDefault();
          const selection = window.getSelection();
          if (selection?.rangeCount) {
            const range = selection.getRangeAt(0);
            range.deleteContents();
            const node = document.createTextNode(text);
            range.insertNode(node);
            range.setStartAfter(node);
            range.collapse(true);
            selection.removeAllRanges();
            selection.addRange(range);
          }
          sendInlineChange();
          return;
        }
        if (!designInteractive || isEditableTarget(e.target)) return;
        const data = e.clipboardData;
        if (!data) return;
        e.preventDefault();
        e.stopPropagation();
        window.parent.postMessage(
          {
            type: MSG.paste,
            text: data.getData("text/plain") || "",
            html: data.getData("text/html") || "",
            aria: data.getData(CLIPBOARD_MIME) || "",
          },
          "*",
        );
      },
      true,
    );
  };

  const previewRules = new Map();
  const previewTargets = new Map();
  const PREVIEW_TARGET_ATTR = "data-aria-composer-preview-target";
  const DISPLAY_STYLE_ID = "aria-composer-display-style";
  const DISPLAY_ATTR = "data-aria-composer-display";
  const FONT_STYLESHEET_ATTR = "data-aria-composer-font-asset";
  const displayStyles = ${JSON.stringify(DISPLAY_MODE_STYLES)};

  const applyDisplayOptions = (mode, accent) => {
    const root = document.documentElement;
    root.setAttribute(DISPLAY_ATTR, mode);
    root.style.setProperty("--aria-composer-accent", accent || "#0f9f73");
    let style = document.getElementById(DISPLAY_STYLE_ID);
    if (!style) {
      style = document.createElement("style");
      style.id = DISPLAY_STYLE_ID;
      style.textContent = displayStyles;
      (document.head || root).appendChild(style);
    }
  };
  const isAllowedFontStylesheetUrl = (href) => {
    let url;
    try {
      url = new URL(href);
    } catch {
      return false;
    }
    if (url.protocol !== "https:") return false;
    if (url.hostname === "fonts.googleapis.com" && /^\\/css2?$/.test(url.pathname)) {
      return true;
    }
    if (
      url.hostname === "cdn.jsdelivr.net" &&
      /^\\/fontsource\\/css\\/[a-z0-9-]+(?::vf)?@[^/]+\\/[a-z0-9.-]+\\.css$/i.test(url.pathname)
    ) {
      return true;
    }
    return false;
  };
  const syncFontStylesheet = (rawUrls) => {
    const allowed = [];
    const seen = new Set();
    for (const raw of Array.isArray(rawUrls) ? rawUrls : []) {
      if (typeof raw !== "string" || !raw.trim()) continue;
      if (!isAllowedFontStylesheetUrl(raw) || seen.has(raw)) continue;
      seen.add(raw);
      allowed.push(raw);
    }
    const existing = Array.from(
      document.querySelectorAll("link[" + FONT_STYLESHEET_ATTR + "]"),
    );
    const keep = new Set();
    for (const href of allowed) {
      let link = existing.find((node) => node.href === href);
      if (!link) {
        link = document.createElement("link");
        link.rel = "stylesheet";
        link.setAttribute(FONT_STYLESHEET_ATTR, "");
        link.addEventListener("load", () => {
          Promise.resolve(document.fonts?.ready).then(queueRects, queueRects);
        }, { once: true });
        (document.head || document.documentElement).appendChild(link);
        link.href = href;
      }
      keep.add(link);
    }
    for (const node of existing) {
      if (!keep.has(node)) node.remove();
    }
    if (!allowed.length) queueRects();
  };
  const renderPreviewRules = () => {
    let style = document.getElementById("aria-composer-preview-style");
    if (!previewRules.size) {
      style?.remove();
      return;
    }
    if (!style) {
      style = document.createElement("style");
      style.id = "aria-composer-preview-style";
      (document.head || document.documentElement)?.appendChild(style);
    }
    style.textContent = [...previewRules.values()]
      .map((rule) => rule.selector + "{" + rule.cssText + "}")
      .join("\\n");
  };

  const previewRuleKey = (path, relativePath) =>
    relativePath ? path + "::" + relativePath : path;

  const clearPreviewTarget = (key) => {
    const record = previewTargets.get(key);
    if (!record) return;
    for (const item of record) {
      const target = item.target;
      if (item.wrappedText && target?.isConnected) {
        target.replaceWith(...target.childNodes);
      } else if (target?.getAttribute?.(PREVIEW_TARGET_ATTR) === key) {
        target.removeAttribute(PREVIEW_TARGET_ATTR);
      }
    }
    previewTargets.delete(key);
  };

  const clearPreviewRule = (key) => {
    previewRules.delete(key);
    clearPreviewTarget(key);
  };

  const sourceNodeForPath = (path, occurrence, relativePath) => {
    const runs = regions.get(path) || [];
    const run = runs[occurrence] || runs[0] || [];
    let node = run.find((candidate) =>
      candidate && candidate.nodeType === 1 && candidate.tagName !== "TEMPLATE"
    ) || null;
    if (!node || !relativePath) return node;
    for (const segment of relativePath.split(".")) {
      const index = Number(segment);
      if (!Number.isInteger(index) || index < 0) return null;
      node = node.childNodes[index] || null;
      if (!node) return null;
    }
    return node;
  };

  const applyPreviewStyle = (request) => {
    const cssText = typeof request.cssText === "string" ? request.cssText : "";
    const relativePath = typeof request.relativePath === "string"
      ? request.relativePath
      : "";
    const key = previewRuleKey(request.path, relativePath);
    if (!relativePath) {
      previewRules.set(key, {
        selector: "[" + PATH_ATTR + '=\"' + CSS.escape(request.path) + '\"]',
        cssText,
      });
      renderPreviewRules();
      queueRects();
      return;
    }
    const records = [];
    const runCount = Math.max((regions.get(request.path) || []).length, 1);
    for (let occurrence = 0; occurrence < runCount; occurrence += 1) {
      let target = sourceNodeForPath(request.path, occurrence, relativePath);
      if (!target) continue;
      if (target.nodeType === 3) {
        const wrapper = document.createElement("span");
        wrapper.setAttribute(PREVIEW_TARGET_ATTR, key);
        target.replaceWith(wrapper);
        wrapper.append(target);
        target = wrapper;
        records.push({ target, wrappedText: true });
      } else if (target.nodeType === 1) {
        target.setAttribute(PREVIEW_TARGET_ATTR, key);
        records.push({ target, wrappedText: false });
      }
    }
    if (!records.length) return;
    previewTargets.set(key, records);
    previewRules.set(key, {
      selector: "[" + PREVIEW_TARGET_ATTR + '=\"' + CSS.escape(key) + '\"]',
      cssText,
    });
    renderPreviewRules();
    queueRects();
  };

  const effectiveBackgroundColor = (target) => {
    let current = target;
    while (current instanceof Element) {
      const color = getComputedStyle(current).backgroundColor.trim();
      if (
        color &&
        color !== "transparent" &&
        !/^rgba\\([^)]*,\\s*0(?:\\.0+)?\\s*\\)$/.test(color) &&
        !/^rgb\\([^)]*\\/\\s*0(?:\\.0+)?\\s*\\)$/.test(color)
      ) {
        return color;
      }
      current = current.parentElement;
    }
    return "rgb(255, 255, 255)";
  };

  const effectiveBackground = (target) => {
    let current = target;
    while (current instanceof Element) {
      const style = getComputedStyle(current);
      const color = style.backgroundColor.trim();
      const image = style.backgroundImage.trim();
      const hasColor =
        color &&
        color !== "transparent" &&
        !/^rgba\\([^)]*,\\s*0(?:\\.0+)?\\s*\\)$/.test(color) &&
        !/^rgb\\([^)]*\\/\\s*0(?:\\.0+)?\\s*\\)$/.test(color);
      if (hasColor || (image && image !== "none")) {
        return style.background.trim() || (hasColor ? color : image);
      }
      current = current.parentElement;
    }
    return "rgb(255, 255, 255)";
  };

  const sendComputedStyle = (request) => {
    const values = {};
    const sourceNode = sourceNodeForPath(
      request.path,
      Number.isInteger(request.occurrence) ? request.occurrence : 0,
      typeof request.relativePath === "string" ? request.relativePath : "",
    );
    const target = sourceNode?.nodeType === 1 ? sourceNode : sourceNode?.parentElement;
    if (target instanceof Element && Array.isArray(request.properties)) {
      const style = getComputedStyle(target);
      for (const property of request.properties.slice(0, 16)) {
        if (typeof property === "string" && /^[-a-zA-Z]+$/.test(property)) {
          values[property] = property === "aria-effective-background"
            ? effectiveBackground(target)
            : property === "aria-effective-background-color"
              ? effectiveBackgroundColor(target)
              : style.getPropertyValue(property).trim();
        }
      }
    }
    window.parent.postMessage(
      {
        type: MSG.computedStyleResponse,
        requestId: request.requestId,
        values,
      },
      "*",
    );
  };

  const sendDropHit = (x, y) => {
    const target = document.elementFromPoint(x, y);
    const hit = nodeAt(target, x, y);
    if (!hit.path) {
      window.parent.postMessage(
        { type: MSG.dropHit, path: null, occurrence: 0, mode: "inside", axis: "vertical", rect: null },
        "*",
      );
      return;
    }
    const rectList = rectsForPath(hit.path) || [];
    const rect = rectList[hit.occurrence] || rectList[0] || null;
    const tagged = target instanceof Element ? target.closest("[" + PATH_ATTR + "]") : null;
    const display = tagged ? getComputedStyle(tagged).display : "block";
    const axis = display === "flex" && tagged && getComputedStyle(tagged).flexDirection.startsWith("row")
      ? "horizontal"
      : "vertical";
    let mode = "inside";
    if (rect) {
      const ratio = axis === "vertical"
        ? (y - rect.y) / Math.max(rect.h, 1)
        : (x - rect.x) / Math.max(rect.w, 1);
      if (ratio < 0.25) mode = "before";
      else if (ratio > 0.75) mode = "after";
    }
    window.parent.postMessage(
      { type: MSG.dropHit, path: hit.path, occurrence: hit.occurrence, mode, axis, rect },
      "*",
    );
  };

  const announceReady = (token = frameToken) => {
    window.parent.postMessage(
      {
        type: MSG.ready,
        version: ${JSON.stringify(ARIA_PROTOCOL_VERSION)},
        bridgeId: ${JSON.stringify(ARIA_BRIDGE_ID)},
        pathname: window.location.pathname,
        frameToken: token,
      },
      "*",
    );
  };

  const VH_RE = /(-?\\d*\\.?\\d+)(vh|svh|lvh|dvh)\\b/g;
  let vhFrozen = false;
  let vhOverrideEl = null;
  let vhRewriteTimer = null;

  const reportPageHeight = () => {
    try {
      const body = document.body;
      let height;
      if (body) {
        const styles = getComputedStyle(body);
        height = body.offsetTop + body.scrollHeight + (parseFloat(styles.marginBottom) || 0);
      } else {
        height = document.documentElement.scrollHeight;
      }
      window.parent.postMessage({ type: MSG.pageHeight, height: Math.ceil(height) }, "*");
    } catch {
      /* ignore */
    }
  };

  const filterVhRule = (rule) => {
    if (rule.cssRules && rule.cssRules.length) {
      let inner = "";
      for (const child of rule.cssRules) inner += filterVhRule(child);
      if (!inner) return "";
      const brace = rule.cssText.indexOf("{");
      if (brace < 0) return "";
      return rule.cssText.slice(0, brace) + "{\\n" + inner + "}\\n";
    }
    const selector = rule.selectorText || rule.keyText;
    if (!rule.style || !selector) return "";
    let decls = "";
    for (const prop of rule.style) {
      const val = rule.style.getPropertyValue(prop);
      const prio = rule.style.getPropertyPriority(prop);
      VH_RE.lastIndex = 0;
      const hasVh = VH_RE.test(val);
      const isFixed = prop === "position" && /fixed/.test(val);
      if (!hasVh && !isFixed) continue;
      VH_RE.lastIndex = 0;
      const newVal = isFixed
        ? "absolute"
        : val.replace(VH_RE, "calc($1 * var(--aria-vh, 1$2))");
      decls += prop + ": " + newVal + (prio ? " !important" : "") + "; ";
    }
    return decls ? selector + " { " + decls + "}\\n" : "";
  };

  const rewriteVhSheets = () => {
    if (!document.head) return;
    let css = "html, body { height: auto !important; }\\n";
    for (const sheet of document.styleSheets) {
      if (sheet.ownerNode === vhOverrideEl) continue;
      let rules;
      try {
        rules = sheet.cssRules;
      } catch {
        continue;
      }
      for (const rule of rules) css += filterVhRule(rule);
    }
    if (!vhOverrideEl) {
      vhOverrideEl = document.createElement("style");
      vhOverrideEl.id = "aria-vh-override";
    }
    if (vhOverrideEl.textContent !== css) vhOverrideEl.textContent = css;
    if (document.head.lastElementChild !== vhOverrideEl) document.head.appendChild(vhOverrideEl);
  };

  const scheduleVhRewrite = () => {
    clearTimeout(vhRewriteTimer);
    vhRewriteTimer = setTimeout(() => {
      rewriteVhSheets();
      reportPageHeight();
    }, 100);
  };

  const freezeViewportHeight = (px) => {
    document.documentElement.style.setProperty("--aria-vh", px / 100 + "px");
    if (!vhFrozen) {
      vhFrozen = true;
      rewriteVhSheets();
      new MutationObserver(scheduleVhRewrite).observe(document.head || document.documentElement, {
        childList: true,
        subtree: true,
      });
      try {
        const observer = new ResizeObserver(reportPageHeight);
        observer.observe(document.documentElement);
        if (document.body) observer.observe(document.body);
      } catch {
        /* old engines: load still reports */
      }
    }
    reportPageHeight();
  };

  window.addEventListener("message", (e) => {
    if (e.source !== window.parent) return;
    const d = e.data;
    if (!d || typeof d !== "object") return;
    if (d.type === MSG.bridgePing && typeof d.frameToken === "string") {
      announceReady(d.frameToken);
    }
    if (d.type === MSG.popoverPreview && (d.targetId === null || typeof d.targetId === "string")) {
      closePreviewPopover(false);
      previewPopoverTargetId = d.open ? d.targetId : null;
      queuePopoverPreview();
    }
    if (
      d.type === MSG.track &&
      Array.isArray(d.paths) &&
      Number.isInteger(d.trackingRevision) &&
      d.trackingRevision >= 0
    ) {
      trackedPaths = d.paths;
      activeScope = typeof d.scope === "string" ? d.scope : "";
      trackingRevision = d.trackingRevision;
      sendRects();
      // Always sample once after layout has had a frame to settle. Further
      // changes are event-driven by mutation, resize, media, and font hooks.
      queueRects();
    }
    if (d.type === MSG.scrollTo && typeof d.path === "string") {
      scrollPathIntoView(
        d.path,
        typeof d.occ === "number" ? d.occ : 0,
        d.policy === "center" ? "center" : "if-needed",
      );
    }
    if (
      d.type === MSG.restoreViewport &&
      Number.isFinite(d.x) &&
      Number.isFinite(d.y)
    ) {
      restoreViewport(d.x, d.y);
    }
    if (d.type === MSG.dragOver && Number.isFinite(d.x) && Number.isFinite(d.y)) {
      sendDropHit(d.x, d.y);
    }
    if (d.type === MSG.dragLeave) {
      window.parent.postMessage(
        { type: MSG.dropHit, path: null, occurrence: 0, mode: "inside", axis: "vertical", rect: null },
        "*",
      );
    }
    if (d.type === MSG.previewStyle && typeof d.path === "string") {
      applyPreviewStyle(d);
    }
    if (d.type === MSG.clearPreviewStyle) {
      if (typeof d.path === "string") {
        clearPreviewRule(previewRuleKey(
          d.path,
          typeof d.relativePath === "string" ? d.relativePath : "",
        ));
      } else {
        for (const key of [...previewRules.keys()]) clearPreviewTarget(key);
        previewRules.clear();
      }
      renderPreviewRules();
      queueRects();
    }
    if (d.type === MSG.syncMotionAssets && typeof d.enabled === "boolean") {
      const cssSelector = 'link[data-aria-motion-asset="css"]';
      const jsSelector = 'script[data-aria-motion-asset="js"]';
      if (!d.enabled) {
        try { window.AriaMotion?.destroy?.(); } catch {}
        try { delete window.AriaMotion; } catch { window.AriaMotion = undefined; }
        document.querySelectorAll(cssSelector + "," + jsSelector).forEach((node) => node.remove());
      } else {
        if (!document.querySelector(cssSelector)) {
          const link = document.createElement("link");
          link.rel = "stylesheet";
          link.href = "/vendor/aria-motion/aria-motion.css";
          link.setAttribute("data-aria-motion-asset", "css");
          document.head.appendChild(link);
        }
        const initialize = () => { try { window.AriaMotion?.init?.(); } catch {} };
        const existingScript = document.querySelector(jsSelector);
        if (window.AriaMotion) initialize();
        else if (existingScript) existingScript.addEventListener("load", initialize, { once: true });
        else {
          const script = document.createElement("script");
          script.src = "/vendor/aria-motion/aria-motion.js";
          script.setAttribute("data-aria-motion-asset", "js");
          script.addEventListener("load", initialize, { once: true });
          document.body.appendChild(script);
        }
      }
    }
    if (d.type === MSG.syncFontStylesheet) {
      const urls = [];
      if (Array.isArray(d.urls)) {
        for (const item of d.urls) {
          if (typeof item === "string") urls.push(item);
        }
      } else if (typeof d.url === "string") {
        urls.push(d.url);
      }
      syncFontStylesheet(urls);
    }
    if (
      d.type === MSG.inlineTextStart && typeof d.requestId === "string" &&
      typeof d.sessionId === "string" && typeof d.path === "string" &&
      Number.isInteger(d.occurrence) && typeof d.value === "string"
    ) {
      startInlineText(d);
    }
    if (
      d.type === MSG.inlineTextStartResult && pendingInlineTextRequest &&
      d.requestId === pendingInlineTextRequest.requestId && d.ok === false
    ) {
      const reason = typeof d.reason === "string" ? d.reason : "Canvas text editing could not start.";
      clearPendingInlineText(reason, false);
      announceInline(reason);
    }
    if (
      d.type === MSG.inlineTextResult && activeInlineText &&
      d.sessionId === activeInlineText.sessionId && Number.isInteger(d.sequence)
    ) {
      if (d.sequence < activeInlineText.sequence) {
        return;
      }
      if (!d.ok) {
        closeInlineText(
          typeof d.value === "string" ? d.value : activeInlineText.originalValue,
          d.reason || "Text edit failed.",
        );
      } else if (d.action === "commit" || d.action === "cancel") {
        closeInlineText(
          typeof d.value === "string" ? d.value : inlineValue(activeInlineText),
          d.action === "cancel"
            ? "Text edit canceled."
            : (typeof d.destination === "string" ? d.destination + " saved." : "Text saved."),
        );
      }
    }
    if (d.type === MSG.patchNodes && Number.isFinite(d.revision) && Array.isArray(d.patches)) {
      patchNodes(d);
    }
    if (d.type === MSG.reconcile && Number.isFinite(d.revision) && Array.isArray(d.paths)) {
      pendingReconciles.set(d.revision, {
        paths: d.paths.filter((path) => typeof path === "string"),
        reloadReason: typeof d.reloadReason === "string" ? d.reloadReason : "",
      });
      // IPC can publish the draft and emit source-ready before this postMessage
      // is handled. Reconcile immediately when that revision is already ready.
      if (d.revision <= latestSourceReadyRevision) {
        reconcileReadyRevision(latestSourceReadyRevision);
      }
    }
    if (
      d.type === MSG.computedStyleRequest &&
      typeof d.requestId === "string" &&
      typeof d.path === "string"
    ) {
      sendComputedStyle(d);
    }
    if (
      d.type === MSG.displayOptions &&
      ["normal", "outlines", "wireframe"].includes(d.mode)
    ) {
      applyDisplayOptions(d.mode, typeof d.accent === "string" ? d.accent : "");
    }
    if (d.type === MSG.designInteraction && typeof d.enabled === "boolean") {
      if (!d.enabled) {
        if (activeInlineText) finishInlineText("commit");
        if (pendingInlineTextRequest) clearPendingInlineText("Canvas text editing was canceled.");
        closePreviewPopover();
      }
      setDesignInteractive(d.enabled);
    }
    if (d.type === MSG.setVh && typeof d.px === "number" && Number.isFinite(d.px)) {
      freezeViewportHeight(d.px);
    }
  });

  const start = () => {
    inlineStatus();
    installTransientScrollbarStyles();
    applyConditionBranches();
    startOutlines();
    new MutationObserver(queuePopoverPreview).observe(document.documentElement, {
      subtree: true,
      childList: true,
      attributes: true,
      attributeFilter: ["id", "popover", "popovertarget"],
    });
    window.addEventListener("scroll", queueViewport, true);
    window.addEventListener("scroll", showTransientScrollbar, true);
    window.addEventListener("pagehide", sendViewport);
    announceReady();
  };
  if (document.readyState === "loading") {
    window.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }
})();
`;
