import { existsSync, mkdirSync, readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import type { ComposerManagedArtifactEdit } from "../../shared/composer/transaction";
import { canonicalDirectory, removePathTracked, resolveWithinRoot, writeTextFileAtomic } from "../pathSafety";
import { markSelfWrite } from "./selfWrite";

export const MOTION_GENERATED_REL = "src/aria/motion.generated.ts";
export const MOTION_CSS_REL = "public/vendor/aria-motion/aria-motion.css";
export const MOTION_JS_REL = "public/vendor/aria-motion/aria-motion.js";

const MOTION_SOURCE_RE = /(?:^|[\s"'`])aria-(?:motion|parallax)(?:[\s"'`-]|$)/;

export const ARIA_MOTION_CSS = String.raw`/* Aria Motion — generated by aria-app. */
:root{--aria-motion-duration-instant:150ms;--aria-motion-duration-fast:300ms;--aria-motion-duration-normal:600ms;--aria-motion-duration-slow:1000ms;--aria-motion-duration-slower:1600ms;--aria-motion-ease-smooth:cubic-bezier(.22,1,.36,1);--aria-motion-ease-spring:cubic-bezier(.34,1.56,.64,1);--aria-motion-ease-linear:linear;--aria-motion-ease-in:cubic-bezier(.4,0,1,1);--aria-motion-ease-out:cubic-bezier(0,0,.2,1);--aria-motion-ease-in-out:cubic-bezier(.4,0,.2,1);--aria-motion-dist-sm:16px;--aria-motion-dist-md:32px;--aria-motion-dist-lg:48px;--aria-motion-dist-xl:64px}
.aria-motion{--aria-motion-duration:var(--aria-motion-duration-normal);--aria-motion-delay:0ms;--aria-motion-ease:var(--aria-motion-ease-smooth);--aria-motion-distance:var(--aria-motion-dist-md)}
.aria-motion-instant{--aria-motion-duration:var(--aria-motion-duration-instant)}.aria-motion-fast{--aria-motion-duration:var(--aria-motion-duration-fast)}.aria-motion-normal{--aria-motion-duration:var(--aria-motion-duration-normal)}.aria-motion-slow{--aria-motion-duration:var(--aria-motion-duration-slow)}.aria-motion-slower{--aria-motion-duration:var(--aria-motion-duration-slower)}
.aria-motion-ease-smooth{--aria-motion-ease:var(--aria-motion-ease-smooth)}.aria-motion-ease-spring{--aria-motion-ease:var(--aria-motion-ease-spring)}.aria-motion-ease-linear{--aria-motion-ease:linear}.aria-motion-ease-in{--aria-motion-ease:var(--aria-motion-ease-in)}.aria-motion-ease-out{--aria-motion-ease:var(--aria-motion-ease-out)}.aria-motion-ease-in-out{--aria-motion-ease:var(--aria-motion-ease-in-out)}
.aria-motion-dist-sm{--aria-motion-distance:var(--aria-motion-dist-sm)}.aria-motion-dist-md{--aria-motion-distance:var(--aria-motion-dist-md)}.aria-motion-dist-lg{--aria-motion-distance:var(--aria-motion-dist-lg)}.aria-motion-dist-xl{--aria-motion-distance:var(--aria-motion-dist-xl)}
.aria-motion-delay-100{--aria-motion-delay:100ms}.aria-motion-delay-200{--aria-motion-delay:200ms}.aria-motion-delay-300{--aria-motion-delay:300ms}.aria-motion-delay-500{--aria-motion-delay:500ms}.aria-motion-delay-700{--aria-motion-delay:700ms}.aria-motion-delay-1000{--aria-motion-delay:1000ms}
.aria-motion.aria-motion-fade:not(.aria-motion-in){opacity:0}.aria-motion.aria-motion-slide-up:not(.aria-motion-in){transform:translateY(var(--aria-motion-distance))}.aria-motion.aria-motion-slide-down:not(.aria-motion-in){transform:translateY(calc(var(--aria-motion-distance)*-1))}.aria-motion.aria-motion-slide-left:not(.aria-motion-in){transform:translateX(var(--aria-motion-distance))}.aria-motion.aria-motion-slide-right:not(.aria-motion-in){transform:translateX(calc(var(--aria-motion-distance)*-1))}.aria-motion.aria-motion-zoom-in:not(.aria-motion-in){transform:scale(.92)}.aria-motion.aria-motion-zoom-out:not(.aria-motion-in){transform:scale(1.08)}.aria-motion.aria-motion-blur:not(.aria-motion-in){filter:blur(8px)}.aria-motion.aria-motion-rotate-in:not(.aria-motion-in){transform:rotate(-6deg)}.aria-motion.aria-motion-flip-up:not(.aria-motion-in){transform:perspective(800px) rotateX(20deg)}.aria-motion.aria-motion-flip-down:not(.aria-motion-in){transform:perspective(800px) rotateX(-20deg)}.aria-motion.aria-motion-flip-left:not(.aria-motion-in){transform:perspective(800px) rotateY(-20deg)}.aria-motion.aria-motion-flip-right:not(.aria-motion-in){transform:perspective(800px) rotateY(20deg)}
.aria-motion.aria-motion-mask-up:not(.aria-motion-in){clip-path:inset(100% 0 0)}.aria-motion.aria-motion-mask-down:not(.aria-motion-in){clip-path:inset(0 0 100%)}.aria-motion.aria-motion-mask-left:not(.aria-motion-in){clip-path:inset(0 100% 0 0)}.aria-motion.aria-motion-mask-right:not(.aria-motion-in){clip-path:inset(0 0 0 100%)}
.aria-motion{transition-property:opacity,transform,filter,clip-path;transition-duration:var(--aria-motion-duration);transition-timing-function:var(--aria-motion-ease);transition-delay:var(--aria-motion-delay)}
.aria-motion-hover:not(.aria-motion-in):hover,.aria-motion-hover:not(.aria-motion-in):focus-visible{opacity:1;transform:none;filter:none;clip-path:none}.aria-motion-hover-lift,.aria-motion-hover-grow,.aria-motion-hover-shrink,.aria-motion-hover-rotate,.aria-motion-hover-tilt,.aria-motion-hover-pop,.aria-motion-hover-press{transition:transform 200ms var(--aria-motion-ease-smooth)}.aria-motion-hover-lift:hover{transform:translateY(-4px)}.aria-motion-hover-grow:hover{transform:scale(1.04)}.aria-motion-hover-shrink:hover{transform:scale(.96)}.aria-motion-hover-rotate:hover{transform:rotate(2deg)}.aria-motion-hover-tilt:hover{transform:perspective(700px) rotateX(2deg) rotateY(-3deg)}.aria-motion-hover-pop:hover{transform:scale(1.04) translateY(-2px)}.aria-motion-hover-press:active{transform:scale(.96)}.aria-motion-hover-glow:hover{filter:drop-shadow(0 0 14px currentColor)}.aria-motion-hover-underline,.aria-motion-hover-sweep,.aria-motion-hover-border{background-size:0 2px;background-repeat:no-repeat;background-position:0 100%;transition:background-size 200ms ease}.aria-motion-hover-underline:hover,.aria-motion-hover-sweep:hover,.aria-motion-hover-border:hover{background-size:100% 2px}
.aria-motion-pulse{animation:aria-motion-pulse 2s ease-in-out infinite}.aria-motion-heartbeat{animation:aria-motion-heartbeat 1.4s ease-in-out infinite}.aria-motion-float{animation:aria-motion-float 3s ease-in-out infinite}.aria-motion-spin{animation:aria-motion-spin 2s linear infinite}.aria-motion-ping{animation:aria-motion-ping 1.5s ease-out infinite}.aria-motion-flash{animation:aria-motion-flash 1.5s ease infinite}.aria-motion-bounce{animation:aria-motion-bounce 1.2s ease infinite}.aria-motion-shake,.aria-motion-vibrate{animation:aria-motion-shake .8s ease infinite}.aria-motion-wobble,.aria-motion-jello,.aria-motion-swing,.aria-motion-rubber,.aria-motion-tada{animation:aria-motion-wobble 1.6s ease-in-out infinite}
@keyframes aria-motion-pulse{50%{transform:scale(1.035)}}@keyframes aria-motion-heartbeat{14%,42%{transform:scale(1.08)}28%,70%{transform:scale(1)}}@keyframes aria-motion-float{50%{transform:translateY(-8px)}}@keyframes aria-motion-spin{to{transform:rotate(360deg)}}@keyframes aria-motion-ping{75%,to{transform:scale(1.12);opacity:0}}@keyframes aria-motion-flash{50%{opacity:.35}}@keyframes aria-motion-bounce{50%{transform:translateY(-8px)}}@keyframes aria-motion-shake{25%{transform:translateX(-3px)}75%{transform:translateX(3px)}}@keyframes aria-motion-wobble{25%{transform:rotate(-2deg)}75%{transform:rotate(2deg)}}
.aria-motion-word,.aria-motion-char{display:inline-block}.aria-motion-word-space{white-space:pre}.aria-motion-stagger>*{transition-delay:calc(var(--aria-motion-delay,0ms) + var(--aria-motion-child-index,0)*var(--aria-motion-stagger,90)*1ms)}
.aria-motion-scrub{--aria-motion-progress:0;transition:none!important}.aria-motion-scrub.aria-motion-fade:not(.aria-motion-in){opacity:var(--aria-motion-progress)}
.aria-parallax{will-change:transform,opacity,filter;transform:translate3d(var(--aria-parallax-x,0),var(--aria-parallax-y,0),0) scale(var(--aria-parallax-scale,1)) rotate(var(--aria-parallax-rotate,0deg));opacity:var(--aria-parallax-opacity,1);filter:blur(var(--aria-parallax-blur,0px))}.aria-parallax-pin{position:sticky;top:0}
@media(max-width:767px){.aria-parallax-mobile-disable{transform:none!important;opacity:1!important;filter:none!important}}
@media(prefers-reduced-motion:reduce){.aria-motion,.aria-motion *,.aria-parallax{animation:none!important;transition:none!important;transform:none!important;filter:none!important;clip-path:none!important;opacity:1!important}}
`;

export const ARIA_MOTION_JS = String.raw`(function(){
  var selector='.aria-motion,.aria-parallax,[data-aria-motion-duration-var],[data-aria-motion-delay-var]',records=new Map(),boot=null;
  function num(el,name,fallback){var v=Number(el.getAttribute(name));return Number.isFinite(v)?v:fallback}
  function signature(el){var classes=Array.from(el.classList).filter(function(name){return (name==='aria-motion'||name.indexOf('aria-motion-')===0||name==='aria-parallax'||name.indexOf('aria-parallax-')===0)&&name!=='aria-motion-in'}).sort();if(el.classList.contains('aria-motion-stagger'))classes.push('children='+el.children.length);if(el.classList.contains('aria-motion-words')||el.classList.contains('aria-motion-chars'))classes.push('text='+(el.textContent||''));var attrs=['data-aria-motion-stagger','data-aria-motion-effect','data-aria-motion-text-stagger','data-aria-motion-scrub','data-aria-motion-strength','data-aria-motion-duration-var','data-aria-motion-delay-var','data-aria-parallax-speed','data-aria-parallax-direction','data-aria-parallax-travel','data-aria-parallax-anchor','data-aria-parallax-easing','data-aria-parallax-start','data-aria-parallax-end','data-aria-parallax-container','data-aria-parallax-pin','data-aria-parallax-pin-duration','data-aria-parallax-pin-offset','data-aria-parallax-group','data-aria-parallax-velocity','data-aria-parallax-mobile-disable'];return classes.join(' ')+'|'+attrs.map(function(name){return name+'='+(el.getAttribute(name)||'')}).join('|')}
  function restoreStyle(el,name,value){if(value)el.style.setProperty(name,value);else el.style.removeProperty(name)}
  function cleanup(el){var record=records.get(el);if(!record)return;record.cleanups.slice().reverse().forEach(function(fn){try{fn()}catch{}});records.delete(el)}
  function setup(el,sig){var cleanups=[];function add(fn){cleanups.push(fn)}
    var duration=el.getAttribute('data-aria-motion-duration-var'),delay=el.getAttribute('data-aria-motion-delay-var');
    if(duration){var oldDuration=el.style.getPropertyValue('--aria-motion-duration');el.style.setProperty('--aria-motion-duration',duration);add(function(){restoreStyle(el,'--aria-motion-duration',oldDuration)})}
    if(delay){var oldDelay=el.style.getPropertyValue('--aria-motion-delay');el.style.setProperty('--aria-motion-delay',delay);add(function(){restoreStyle(el,'--aria-motion-delay',oldDelay)})}
    if(el.classList.contains('aria-motion-words')||el.classList.contains('aria-motion-chars')){var originalText=el.textContent||'',words=el.classList.contains('aria-motion-words'),parts=words?originalText.split(/(\s+)/):Array.from(originalText),effects=(el.getAttribute('data-aria-motion-effect')||'').split(/\s+/).filter(Boolean);if(!el.children.length){el.textContent='';parts.forEach(function(part,index){var span=document.createElement('span');span.textContent=part;span.className=/^\s+$/.test(part)?'aria-motion-word-space':(words?'aria-motion-word':'aria-motion-char')+' '+effects.join(' ');span.style.setProperty('--aria-motion-child-index',String(index));el.appendChild(span)});el.setAttribute('data-aria-motion-split','true');add(function(){var text=el.textContent||originalText;el.textContent=text;el.removeAttribute('data-aria-motion-split')})}}
    if(el.classList.contains('aria-motion-stagger')){var oldStagger=el.style.getPropertyValue('--aria-motion-stagger'),children=Array.from(el.children),oldIndexes=children.map(function(child){return child.style.getPropertyValue('--aria-motion-child-index')});var interval=num(el,'data-aria-motion-stagger',90);children.forEach(function(child,index){child.style.setProperty('--aria-motion-child-index',String(index))});el.style.setProperty('--aria-motion-stagger',String(interval));add(function(){restoreStyle(el,'--aria-motion-stagger',oldStagger);children.forEach(function(child,index){restoreStyle(child,'--aria-motion-child-index',oldIndexes[index])})})}
    if(el.classList.contains('aria-motion-now'))el.classList.add('aria-motion-in');
    if(el.classList.contains('aria-motion-reveal')){if(typeof IntersectionObserver==='function'){var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('aria-motion-in');io.unobserve(entry.target)}})},{threshold:.12});io.observe(el);add(function(){io.disconnect()})}else el.classList.add('aria-motion-in')}
    if(el.classList.contains('aria-motion-click')){var click=function(){el.classList.toggle('aria-motion-in')};el.addEventListener('click',click);add(function(){el.removeEventListener('click',click)})}
    if(el.classList.contains('aria-motion-scrub')){var oldProgress=el.style.getPropertyValue('--aria-motion-progress'),scrub=function(){var r=el.getBoundingClientRect(),travel=num(el,'data-aria-motion-scrub',200),p=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+Math.max(travel,r.height))));el.style.setProperty('--aria-motion-progress',String(p));if(p>=.98)el.classList.add('aria-motion-in');else el.classList.remove('aria-motion-in')};window.addEventListener('scroll',scrub,{passive:true});scrub();add(function(){window.removeEventListener('scroll',scrub);restoreStyle(el,'--aria-motion-progress',oldProgress)})}
    if(el.classList.contains('aria-motion-magnetic')){var oldTransform=el.style.transform,strength=num(el,'data-aria-motion-strength',.35),move=function(event){var r=el.getBoundingClientRect(),x=(event.clientX-r.left-r.width/2)*strength,y=(event.clientY-r.top-r.height/2)*strength;el.style.transform='translate3d('+x+'px,'+y+'px,0)'},leave=function(){el.style.transform=oldTransform};el.addEventListener('pointermove',move);el.addEventListener('pointerleave',leave);add(function(){el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',leave);el.style.transform=oldTransform})}
    if(el.classList.contains('aria-parallax')){var names=['--aria-parallax-x','--aria-parallax-y','--aria-parallax-opacity','--aria-parallax-scale','--aria-parallax-blur','--aria-parallax-rotate'],oldValues=names.map(function(name){return el.style.getPropertyValue(name)}),parallax=function(){if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;var r=el.getBoundingClientRect(),travel=num(el,'data-aria-parallax-travel',200),speed=num(el,'data-aria-parallax-speed',1),progress=Math.max(-1,Math.min(1,(innerHeight/2-(r.top+r.height/2))/innerHeight)),amount=progress*travel*speed,dir=el.getAttribute('data-aria-parallax-direction')||'up';el.style.setProperty('--aria-parallax-x',(dir==='left'?-amount:dir==='right'?amount:0)+'px');el.style.setProperty('--aria-parallax-y',(dir==='up'?-amount:dir==='down'?amount:0)+'px');if(el.classList.contains('aria-parallax-fx-opacity'))el.style.setProperty('--aria-parallax-opacity',String(Math.max(0,Math.min(1,.5+progress))));if(el.classList.contains('aria-parallax-fx-scale'))el.style.setProperty('--aria-parallax-scale',String(1+progress*.08));if(el.classList.contains('aria-parallax-fx-blur'))el.style.setProperty('--aria-parallax-blur',Math.max(0,(1-progress)*4)+'px');if(el.classList.contains('aria-parallax-fx-rotate'))el.style.setProperty('--aria-parallax-rotate',(progress*4)+'deg')};window.addEventListener('scroll',parallax,{passive:true});parallax();add(function(){window.removeEventListener('scroll',parallax);names.forEach(function(name,index){restoreStyle(el,name,oldValues[index])})})}
    add(function(){el.classList.remove('aria-motion-in')});records.set(el,{signature:sig,cleanups:cleanups})
  }
  function elements(root){var found=[];if(root&&root.nodeType===1&&root.matches(selector))found.push(root);if(root&&root.querySelectorAll)found=found.concat(Array.from(root.querySelectorAll(selector)));return found}
  function init(root){root=root||document;var active=new Set(elements(root));records.forEach(function(record,el){if(!el.isConnected||(root===document&&!active.has(el))||(root!==document&&root.contains&&root.contains(el)&&!active.has(el)))cleanup(el)});active.forEach(function(el){var sig=signature(el),record=records.get(el);if(record&&record.signature===sig)return;if(record)cleanup(el);setup(el,sig)})}
  function destroy(root){if(boot){document.removeEventListener('DOMContentLoaded',boot);boot=null}Array.from(records.keys()).forEach(function(el){if(!root||root===document||el===root||(root.contains&&root.contains(el)))cleanup(el)})}
  window.AriaMotion={init:init,destroy:destroy};
  if(document.readyState==='loading'){boot=function(){boot=null;init(document)};document.addEventListener('DOMContentLoaded',boot,{once:true})}else init(document);
})();
`;

function walkAstroFiles(root: string): string[] {
  const src = resolveWithinRoot(root, path.join(root, "src"), { allowMissing: true });
  if (!existsSync(src)) return [];
  const files: string[] = [];
  const visit = (directory: string) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) visit(absolute);
      else if (entry.isFile() && entry.name.endsWith(".astro")) files.push(absolute);
    }
  };
  visit(src);
  return files;
}

export function projectHasMotion(
  projectPath: string,
  pendingSources: ReadonlyMap<string, string> = new Map(),
): boolean {
  const root = canonicalDirectory(projectPath);
  for (const absolute of walkAstroFiles(root)) {
    const relative = path.relative(root, absolute).split(path.sep).join("/");
    const source = pendingSources.get(relative) ?? readFileSync(absolute, "utf8");
    if (MOTION_SOURCE_RE.test(source)) return true;
  }
  for (const [relative, source] of pendingSources) {
    if (relative.endsWith(".astro") && MOTION_SOURCE_RE.test(source)) return true;
  }
  return false;
}

function generatedSource(enabled: boolean): string {
  return [
    "/** Aria-generated motion injection slots — do not edit. */",
    "export const ariaMotionSlots = {",
    `  header: ${JSON.stringify(enabled ? '<link rel="stylesheet" href="/vendor/aria-motion/aria-motion.css" data-aria-motion-asset="css">' : "")},`,
    `  footer: ${JSON.stringify(enabled ? '<script src="/vendor/aria-motion/aria-motion.js" defer data-aria-motion-asset="js"></script>' : "")},`,
    "} as const;",
    "",
  ].join("\n");
}

function mtime(root: string, relativeFile: string): number | null {
  const file = resolveWithinRoot(root, path.join(root, ...relativeFile.split("/")), { allowMissing: true });
  return existsSync(file) ? Math.floor(statSync(file).mtimeMs) : null;
}

export function buildMotionArtifactEdits(
  projectPath: string,
  pendingSources: ReadonlyMap<string, string> = new Map(),
): ComposerManagedArtifactEdit[] {
  const root = canonicalDirectory(projectPath);
  const enabled = projectHasMotion(root, pendingSources);
  return [
    { owner: "motion", relativeFile: MOTION_GENERATED_REL, content: generatedSource(enabled), expectedMtimeMs: mtime(root, MOTION_GENERATED_REL) },
    { owner: "motion", relativeFile: MOTION_CSS_REL, content: enabled ? ARIA_MOTION_CSS : null, expectedMtimeMs: mtime(root, MOTION_CSS_REL) },
    { owner: "motion", relativeFile: MOTION_JS_REL, content: enabled ? ARIA_MOTION_JS : null, expectedMtimeMs: mtime(root, MOTION_JS_REL) },
  ];
}

export function syncMotionArtifacts(projectPath: string): void {
  const root = canonicalDirectory(projectPath);
  for (const artifact of buildMotionArtifactEdits(root)) {
    const target = resolveWithinRoot(root, path.join(root, ...artifact.relativeFile.split("/")), { allowMissing: true, rejectFinalSymlink: true });
    if (artifact.content === null) {
      if (existsSync(target)) {
        markSelfWrite(target);
        removePathTracked(target, { force: true });
      }
      continue;
    }
    mkdirSync(path.dirname(target), { recursive: true });
    if (!existsSync(target) || readFileSync(target, "utf8") !== artifact.content) {
      markSelfWrite(target);
      writeTextFileAtomic(target, artifact.content);
    }
  }
}
