import { describe, expect, it } from "vitest";
import { registerAgentIpc } from "../agent/ipc";
import { registerAppIpc } from "../app/ipc";
import { registerCmsEntriesIpc } from "../cms/ipc/entries";
import { registerCmsImportsIpc } from "../cms/ipc/imports";
import { registerComposerIpc } from "../composer/ipc";
import { registerDesignIpc } from "../design/ipc";
import { registerGitIpc } from "../git/ipc";
import { registerHistoryIpc } from "../history/ipc";
import { registerMediaIpc } from "../media/ipc";
import { mutationMetaForChannel } from "../mutations";
import { registerProjectIpc } from "../project/ipc";
import { registerSiteDiscoveryIpc } from "../site/ipc/discovery";
import { registerSiteSettingsIpc } from "../site/ipc/settings";
import { registerStudioDocumentsIpc } from "../studio/ipc";
import { registerTerminalIpc } from "../terminal/ipc";
import { registerThumbsIpc } from "../thumbs/ipc";
import { registerCollectionsIpc } from "../workspace/ipc/collections";
import { registerExportsIpc } from "../workspace/ipc/exports";
import { registerWorkspaceIpc } from "../workspace/ipc/core";
import type {
  IpcHandleOptions,
  IpcRegistrar,
  IpcRuntimeContext,
} from "./registrar";

const EXPECTED_IPC_CHANNELS = [
  "add_recent",
  "agent:cancelChat",
  "agent:clearProviderCredentials",
  "agent:confirmInsecureProviderCredentials",
  "agent:getAvailability",
  "agent:getCredentialStatuses",
  "agent:getSettings",
  "agent:listCatalogModels",
  "agent:patchSettings",
  "agent:registerRendererHost",
  "agent:removeInferenceProvider",
  "agent:rendererToolResult",
  "agent:setProviderCredentials",
  "agent:startChat",
  "appearance:get",
  "appearance:set",
  "cancel_create_astro_project",
  "clipboard:read_composer",
  "clipboard:write_composer",
  "clipboard:write_text",
  "cms:archive_entry",
  "cms:check_slug",
  "cms:create_entry",
  "cms:create_translation_drafts",
  "cms:delete_collection_entries",
  "cms:delete_collections",
  "cms:delete_entry",
  "cms:duplicate_entry",
  "cms:get_entry",
  "cms:import_markdown",
  "cms:import_markdown_batch",
  "cms:list_entries",
  "cms:list_revisions",
  "cms:migrate_collection",
  "cms:preview_markdown_import",
  "cms:preview_markdown_import_batch",
  "cms:publish_entry",
  "cms:restore_revision",
  "cms:seed_blog",
  "cms:unpublish_entry",
  "cms:update_entry",
  "cms:wordpress_import_analyze",
  "cms:wordpress_import_apply",
  "cms:wordpress_import_cancel",
  "cms:wordpress_import_cleanup_expired",
  "cms:wordpress_import_delete_batch",
  "cms:wordpress_import_get_batch",
  "cms:wordpress_import_get_events",
  "cms:wordpress_import_get_report",
  "cms:wordpress_import_list_batches",
  "cms:wordpress_import_upload",
  "composer:analyze_source",
  "composer:apply_project_data_cutover",
  "composer:apply_translation_cutover",
  "composer:assess_project_data_adoption",
  "composer:assess_translation_adoption",
  "composer:clear_preview_draft",
  "composer:commit_transaction",
  "composer:complete_code",
  "composer:create_project_data_draft",
  "composer:detect_frameworks",
  "composer:edit_project_data",
  "composer:edit_translation_value",
  "composer:extract_prop_schema",
  "composer:inspect_project_data",
  "composer:list_translation_catalogs",
  "composer:parse_page",
  "composer:prepare_component_preview",
  "composer:reveal_project_data",
  "composer:set_preview_draft",
  "composer:write_component_control_metadata",
  "composer:write_page",
  "create_astro_project",
  "design:apply_token_mutation",
  "design:create_stylesheet",
  "design:delete_font",
  "design:delete_stylesheet",
  "design:detect_fontsource_runtime",
  "design:detect_icon_runtime",
  "design:ensure_entry",
  "design:get_snapshot",
  "design:list_stylesheets",
  "design:patch",
  "design:preview_token_mutation",
  "design:read_stylesheet",
  "design:rename_class",
  "design:resolve_icons",
  "design:reveal_font",
  "design:reveal_stylesheet",
  "design:scan_class_usage",
  "design:search_icons",
  "design:select_token_source",
  "design:upload_font",
  "design:write_stylesheet",
  "get_version",
  "git:checkout",
  "git:commit",
  "git:createBranch",
  "git:diffFile",
  "git:init",
  "git:listBranches",
  "git:push",
  "git:status",
  "history:list",
  "history:redo",
  "history:restore",
  "history:undo",
  "list_recents",
  "media:delete",
  "media:delete_variant",
  "media:duplicate",
  "media:get_grouping",
  "media:get_playable_url",
  "media:get_transform_state",
  "media:list",
  "media:preview",
  "media:rename",
  "media:resolve",
  "media:reveal",
  "media:save_profile",
  "media:save_variant",
  "media:save_variant_with_profile",
  "media:update_grouping",
  "media:upload",
  "media:usages",
  "open_project_dialog",
  "open_project_window",
  "open_url",
  "pick_new_project_dir",
  "remove_recent",
  "renderer:ready",
  "search:project",
  "sessions:close",
  "sessions:confirmTrustAndOpen",
  "sessions:installDeps",
  "sessions:list",
  "sessions:open",
  "sessions:restart",
  "sessions:revokeTrust",
  "sessions:start",
  "sessions:stop",
  "shell:reveal_path",
  "terminal:create",
  "terminal:dispose",
  "terminal:resize",
  "terminal:restart",
  "terminal:write",
  "thumbs:cancelWarm",
  "thumbs:capture",
  "thumbs:getComponent",
  "thumbs:getLayout",
  "thumbs:getPage",
  "thumbs:getProject",
  "thumbs:prioritizeComponents",
  "thumbs:warmComponents",
  "thumbs:warmLayouts",
  "thumbs:warmPages",
  "window:close",
  "window:is_fullscreen",
  "window:set_fullscreen",
  "workspace:assess_collection_migration",
  "workspace:cancel_collection_refresh",
  "workspace:confirm_seo_takeover",
  "workspace:create_component",
  "workspace:create_layout",
  "workspace:create_page",
  "workspace:create_redirect",
  "workspace:delete_component",
  "workspace:delete_component_folder",
  "workspace:delete_page",
  "workspace:delete_redirect",
  "workspace:delete_studio_document",
  "workspace:duplicate_studio_document",
  "workspace:favicon_preview",
  "workspace:flatten_redirect_chain",
  "workspace:get_collections",
  "workspace:get_component_grouping",
  "workspace:get_discovery_artifacts",
  "workspace:get_discovery_baseline",
  "workspace:get_discovery_report",
  "workspace:get_external_entry",
  "workspace:get_pages_meta",
  "workspace:get_site_settings",
  "workspace:import_redirects_csv",
  "workspace:inspect_component",
  "workspace:inspect_layouts",
  "workspace:list_external_entries",
  "workspace:list_redirect_targets",
  "workspace:list_redirects",
  "workspace:pick_favicon",
  "workspace:refresh_collection_source",
  "workspace:rename_component_folder",
  "workspace:resolve_component",
  "workspace:resolve_page",
  "workspace:resolve_studio_document",
  "workspace:reveal_component",
  "workspace:reveal_page",
  "workspace:reveal_studio_document",
  "workspace:scan",
  "workspace:scan_injections",
  "workspace:scan_seo_sources",
  "workspace:seo_takeover_checklist",
  "workspace:set_site_settings",
  "workspace:site_export_create",
  "workspace:site_export_delete",
  "workspace:site_export_inventory",
  "workspace:site_export_list",
  "workspace:site_export_reveal",
  "workspace:site_export_save_as",
  "workspace:update_analytics",
  "workspace:update_collections",
  "workspace:update_component_grouping",
  "workspace:update_content_localization",
  "workspace:update_discovery",
  "workspace:update_page_config",
  "workspace:update_pages_meta",
  "workspace:update_redirect",
  "workspace:update_seo_defaults",
  "workspace:update_source_injection"
] as const;

const EXPECTED_MUTATION_CHANNELS = [
  "cms:archive_entry",
  "cms:create_entry",
  "cms:create_translation_drafts",
  "cms:delete_collection_entries",
  "cms:delete_collections",
  "cms:delete_entry",
  "cms:duplicate_entry",
  "cms:import_markdown",
  "cms:migrate_collection",
  "cms:publish_entry",
  "cms:restore_revision",
  "cms:seed_blog",
  "cms:unpublish_entry",
  "cms:update_entry",
  "composer:apply_translation_cutover",
  "composer:commit_transaction",
  "composer:edit_translation_value",
  "composer:write_page",
  "design:create_stylesheet",
  "design:delete_font",
  "design:delete_stylesheet",
  "design:ensure_entry",
  "design:patch",
  "design:rename_class",
  "design:upload_font",
  "design:write_stylesheet",
  "media:delete",
  "media:delete_variant",
  "media:duplicate",
  "media:rename",
  "media:save_profile",
  "media:save_variant",
  "media:save_variant_with_profile",
  "media:update_grouping",
  "workspace:confirm_seo_takeover",
  "workspace:create_component",
  "workspace:create_page",
  "workspace:create_redirect",
  "workspace:delete_component",
  "workspace:delete_component_folder",
  "workspace:delete_page",
  "workspace:delete_redirect",
  "workspace:delete_studio_document",
  "workspace:duplicate_studio_document",
  "workspace:flatten_redirect_chain",
  "workspace:import_redirects_csv",
  "workspace:scan_seo_sources",
  "workspace:set_site_settings",
  "workspace:update_analytics",
  "workspace:update_collections",
  "workspace:update_component_grouping",
  "workspace:update_discovery",
  "workspace:update_page_config",
  "workspace:update_pages_meta",
  "workspace:update_redirect",
  "workspace:update_seo_defaults",
  "workspace:update_source_injection",
] as const;

const registerDomainIpc = [
  registerAppIpc,
  registerProjectIpc,
  registerThumbsIpc,
  registerHistoryIpc,
  registerWorkspaceIpc,
  registerCollectionsIpc,
  registerCmsEntriesIpc,
  registerCmsImportsIpc,
  registerExportsIpc,
  registerMediaIpc,
  registerSiteSettingsIpc,
  registerSiteDiscoveryIpc,
  registerStudioDocumentsIpc,
  registerComposerIpc,
  registerDesignIpc,
  registerGitIpc,
  registerTerminalIpc,
  registerAgentIpc,
] as const;

describe("main-process IPC registration", () => {
  it("composes the complete unique channel inventory with unchanged policy", () => {
    const registrations = new Map<string, IpcHandleOptions | undefined>();
    const registrar: IpcRegistrar = {
      handle(channel, _listener, options) {
        if (registrations.has(channel)) {
          throw new Error(`Duplicate IPC channel: ${channel}`);
        }
        registrations.set(channel, options);
      },
    };
    const context = {
      userDataPath: "/tmp/aria-ipc-registration-test",
      getVersion: () => "test",
      createWindow: () => ({}) as ReturnType<IpcRuntimeContext["createWindow"]>,
      refreshApplicationMenu: () => undefined,
      senderWindow: () => null,
    } satisfies IpcRuntimeContext;

    for (const register of registerDomainIpc) register(registrar, context);

    const channels = [...registrations.keys()].sort();
    expect(channels).toEqual(EXPECTED_IPC_CHANNELS);
    expect(
      channels.filter(
        (channel) => registrations.get(channel)?.beforeHandshake === true,
      ),
    ).toEqual(["renderer:ready"]);
    expect(
      channels.filter(
        (channel) => registrations.get(channel)?.duringShutdown === true,
      ),
    ).toEqual(["thumbs:cancelWarm"]);
    expect(
      channels.filter((channel) => mutationMetaForChannel(channel, []) !== null),
    ).toEqual(EXPECTED_MUTATION_CHANNELS);
  });
});
